letterboxds-top-500:
  title: "Letterboxd's Top 500 Films"
  description: "The 500 highest-rated narrative feature films on Letterboxd."
  enabled: true
  users:
    - username: "official"
      slug: "letterboxds-top-500-films"
