// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  CinemasGetAllCinemasResponse,
  FriendsSendFriendRequestData,
  FriendsSendFriendRequestResponse,
  FriendsAcceptFriendRequestData,
  FriendsAcceptFriendRequestResponse,
  FriendsDeclineFriendRequestData,
  FriendsDeclineFriendRequestResponse,
  FriendsCancelFriendRequestData,
  FriendsCancelFriendRequestResponse,
  FriendsRemoveFriendData,
  FriendsRemoveFriendResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  MeGetCurrentUserResponse,
  MeDeleteUserMeResponse,
  MeUpdateUserMeData,
  MeUpdateUserMeResponse,
  MeGetFilterPresetsData,
  MeGetFilterPresetsResponse,
  MeSaveFilterPresetData,
  MeSaveFilterPresetResponse,
  MeGetFavoriteFilterPresetData,
  MeGetFavoriteFilterPresetResponse,
  MeClearFavoriteFilterPresetData,
  MeClearFavoriteFilterPresetResponse,
  MeSetFavoriteFilterPresetData,
  MeSetFavoriteFilterPresetResponse,
  MeDeleteFilterPresetData,
  MeDeleteFilterPresetResponse,
  MeGetCinemaPresetsResponse,
  MeSaveCinemaPresetData,
  MeSaveCinemaPresetResponse,
  MeGetFavoriteCinemaPresetResponse,
  MeClearFavoriteCinemaPresetResponse,
  MeSetFavoriteCinemaPresetData,
  MeSetFavoriteCinemaPresetResponse,
  MeDeleteCinemaPresetData,
  MeDeleteCinemaPresetResponse,
  MeUpdatePasswordMeData,
  MeUpdatePasswordMeResponse,
  MeGetMyShowtimesData,
  MeGetMyShowtimesResponse,
  MeGetMyShowtimePingsData,
  MeGetMyShowtimePingsResponse,
  MeGetMyUnseenShowtimePingCountResponse,
  MeMarkMyShowtimePingsSeenResponse,
  MeDeleteMyShowtimePingData,
  MeDeleteMyShowtimePingResponse,
  MeSyncWatchlistResponse,
  MeGetFriendsResponse,
  MeGetSentFriendRequestsResponse,
  MeGetReceivedFriendRequestsResponse,
  MeGetCinemaSelectionsResponse,
  MeSetCinemaSelectionsData,
  MeSetCinemaSelectionsResponse,
  MeRegisterPushTokenData,
  MeRegisterPushTokenResponse,
  MoviesReadMoviesData,
  MoviesReadMoviesResponse,
  MoviesReadMovieShowtimesData,
  MoviesReadMovieShowtimesResponse,
  MoviesReadMovieData,
  MoviesReadMovieResponse,
  ShowtimesUpdateShowtimeSelectionData,
  ShowtimesUpdateShowtimeSelectionResponse,
  ShowtimesPingFriendForShowtimeData,
  ShowtimesPingFriendForShowtimeResponse,
  ShowtimesGetPingedFriendIdsForShowtimeData,
  ShowtimesGetPingedFriendIdsForShowtimeResponse,
  ShowtimesGetShowtimeVisibilityData,
  ShowtimesGetShowtimeVisibilityResponse,
  ShowtimesUpdateShowtimeVisibilityData,
  ShowtimesUpdateShowtimeVisibilityResponse,
  ShowtimesGetMainPageShowtimesData,
  ShowtimesGetMainPageShowtimesResponse,
  UsersSearchUsersData,
  UsersSearchUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersGetUserData,
  UsersGetUserResponse,
  UsersGetUserSelectedShowtimesData,
  UsersGetUserSelectedShowtimesResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
  UtilsOverrideTmdbCacheEntryData,
  UtilsOverrideTmdbCacheEntryResponse,
} from "./types.gen"

export class CinemasService {
  /**
   * Get All Cinemas
   * @returns CinemaPublic Successful Response
   * @throws ApiError
   */
  public static getAllCinemas(): CancelablePromise<CinemasGetAllCinemasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/cinemas/",
    })
  }
}

export class FriendsService {
  /**
   * Send Friend Request
   * @param data The data for the request.
   * @param data.receiverId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static sendFriendRequest(
    data: FriendsSendFriendRequestData,
  ): CancelablePromise<FriendsSendFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/request/{receiver_id}",
      path: {
        receiver_id: data.receiverId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Accept Friend Request
   * @param data The data for the request.
   * @param data.senderId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static acceptFriendRequest(
    data: FriendsAcceptFriendRequestData,
  ): CancelablePromise<FriendsAcceptFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/accept/{sender_id}",
      path: {
        sender_id: data.senderId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Decline Friend Request
   * @param data The data for the request.
   * @param data.senderId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static declineFriendRequest(
    data: FriendsDeclineFriendRequestData,
  ): CancelablePromise<FriendsDeclineFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/decline/{sender_id}",
      path: {
        sender_id: data.senderId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Cancel Friend Request
   * @param data The data for the request.
   * @param data.receiverId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static cancelFriendRequest(
    data: FriendsCancelFriendRequestData,
  ): CancelablePromise<FriendsCancelFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/friends/cancel/{receiver_id}",
      path: {
        receiver_id: data.receiverId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remove Friend
   * @param data The data for the request.
   * @param data.friendId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static removeFriend(
    data: FriendsRemoveFriendData,
  ): CancelablePromise<FriendsRemoveFriendResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/friends/{friend_id}",
      path: {
        friend_id: data.friendId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MeService {
  /**
   * Get Current User
   * @returns UserMe Successful Response
   * @throws ApiError
   */
  public static getCurrentUser(): CancelablePromise<MeGetCurrentUserResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/",
    })
  }

  /**
   * Delete User Me
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<MeDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/",
    })
  }

  /**
   * Update User Me
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserMe Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: MeUpdateUserMeData,
  ): CancelablePromise<MeUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/me/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Filter Presets
   * @param data The data for the request.
   * @param data.scope
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static getFilterPresets(
    data: MeGetFilterPresetsData,
  ): CancelablePromise<MeGetFilterPresetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/filter-presets",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Save Filter Preset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static saveFilterPreset(
    data: MeSaveFilterPresetData,
  ): CancelablePromise<MeSaveFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/filter-presets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Filter Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteFilterPreset(
    data: MeGetFavoriteFilterPresetData,
  ): CancelablePromise<MeGetFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/filter-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Clear Favorite Filter Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteFilterPreset(
    data: MeClearFavoriteFilterPresetData,
  ): CancelablePromise<MeClearFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/filter-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Set Favorite Filter Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteFilterPreset(
    data: MeSetFavoriteFilterPresetData,
  ): CancelablePromise<MeSetFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/filter-presets/{preset_id}/favorite",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Filter Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFilterPreset(
    data: MeDeleteFilterPresetData,
  ): CancelablePromise<MeDeleteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/filter-presets/{preset_id}",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Cinema Presets
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static getCinemaPresets(): CancelablePromise<MeGetCinemaPresetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinema-presets",
    })
  }

  /**
   * Save Cinema Preset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static saveCinemaPreset(
    data: MeSaveCinemaPresetData,
  ): CancelablePromise<MeSaveCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/cinema-presets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Cinema Preset
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteCinemaPreset(): CancelablePromise<MeGetFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinema-presets/favorite",
    })
  }

  /**
   * Clear Favorite Cinema Preset
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteCinemaPreset(): CancelablePromise<MeClearFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/cinema-presets/favorite",
    })
  }

  /**
   * Set Favorite Cinema Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteCinemaPreset(
    data: MeSetFavoriteCinemaPresetData,
  ): CancelablePromise<MeSetFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/cinema-presets/{preset_id}/favorite",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Cinema Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCinemaPreset(
    data: MeDeleteCinemaPresetData,
  ): CancelablePromise<MeDeleteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/cinema-presets/{preset_id}",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: MeUpdatePasswordMeData,
  ): CancelablePromise<MeUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Showtimes
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getMyShowtimes(
    data: MeGetMyShowtimesData = {},
  ): CancelablePromise<MeGetMyShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/showtimes",
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Showtime Pings
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.sortBy
   * @returns ShowtimePingPublic Successful Response
   * @throws ApiError
   */
  public static getMyShowtimePings(
    data: MeGetMyShowtimePingsData = {},
  ): CancelablePromise<MeGetMyShowtimePingsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/pings",
      query: {
        limit: data.limit,
        offset: data.offset,
        sort_by: data.sortBy,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Unseen Showtime Ping Count
   * @returns number Successful Response
   * @throws ApiError
   */
  public static getMyUnseenShowtimePingCount(): CancelablePromise<MeGetMyUnseenShowtimePingCountResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/pings/unseen-count",
    })
  }

  /**
   * Mark My Showtime Pings Seen
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static markMyShowtimePingsSeen(): CancelablePromise<MeMarkMyShowtimePingsSeenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/pings/mark-seen",
    })
  }

  /**
   * Delete My Showtime Ping
   * @param data The data for the request.
   * @param data.pingId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteMyShowtimePing(
    data: MeDeleteMyShowtimePingData,
  ): CancelablePromise<MeDeleteMyShowtimePingResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/pings/{ping_id}",
      path: {
        ping_id: data.pingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Sync Watchlist
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static syncWatchlist(): CancelablePromise<MeSyncWatchlistResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/watchlist",
    })
  }

  /**
   * Get Friends
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getFriends(): CancelablePromise<MeGetFriendsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/friends",
    })
  }

  /**
   * Get Sent Friend Requests
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getSentFriendRequests(): CancelablePromise<MeGetSentFriendRequestsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/requests/sent",
    })
  }

  /**
   * Get Received Friend Requests
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getReceivedFriendRequests(): CancelablePromise<MeGetReceivedFriendRequestsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/requests/received",
    })
  }

  /**
   * Get Cinema Selections
   * @returns number Successful Response
   * @throws ApiError
   */
  public static getCinemaSelections(): CancelablePromise<MeGetCinemaSelectionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinemas",
    })
  }

  /**
   * Set Cinema Selections
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static setCinemaSelections(
    data: MeSetCinemaSelectionsData,
  ): CancelablePromise<MeSetCinemaSelectionsResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/cinemas",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register Push Token
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static registerPushToken(
    data: MeRegisterPushTokenData,
  ): CancelablePromise<MeRegisterPushTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/push-tokens",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MoviesService {
  /**
   * Read Movies
   * @param data The data for the request.
   * @param data.offset
   * @param data.limit
   * @param data.showtimeLimit
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns MovieSummaryLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovies(
    data: MoviesReadMoviesData = {},
  ): CancelablePromise<MoviesReadMoviesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/",
      query: {
        offset: data.offset,
        limit: data.limit,
        showtime_limit: data.showtimeLimit,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Movie Showtimes
   * @param data The data for the request.
   * @param data.id
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns ShowtimeInMovieLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovieShowtimes(
    data: MoviesReadMovieShowtimesData,
  ): CancelablePromise<MoviesReadMovieShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/{id}/showtimes",
      path: {
        id: data.id,
      },
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Movie
   * @param data The data for the request.
   * @param data.id
   * @param data.showtimeLimit
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns MovieLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovie(
    data: MoviesReadMovieData,
  ): CancelablePromise<MoviesReadMovieResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/{id}",
      path: {
        id: data.id,
      },
      query: {
        showtime_limit: data.showtimeLimit,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ShowtimesService {
  /**
   * Update Showtime Selection
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.requestBody
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static updateShowtimeSelection(
    data: ShowtimesUpdateShowtimeSelectionData,
  ): CancelablePromise<ShowtimesUpdateShowtimeSelectionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/showtimes/selection/{showtime_id}",
      path: {
        showtime_id: data.showtimeId,
      },
      query: {
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Ping Friend For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.friendId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static pingFriendForShowtime(
    data: ShowtimesPingFriendForShowtimeData,
  ): CancelablePromise<ShowtimesPingFriendForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/showtimes/{showtime_id}/ping/{friend_id}",
      path: {
        showtime_id: data.showtimeId,
        friend_id: data.friendId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Pinged Friend Ids For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns string Successful Response
   * @throws ApiError
   */
  public static getPingedFriendIdsForShowtime(
    data: ShowtimesGetPingedFriendIdsForShowtimeData,
  ): CancelablePromise<ShowtimesGetPingedFriendIdsForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}/pinged-friends",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Showtime Visibility
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns ShowtimeVisibilityPublic Successful Response
   * @throws ApiError
   */
  public static getShowtimeVisibility(
    data: ShowtimesGetShowtimeVisibilityData,
  ): CancelablePromise<ShowtimesGetShowtimeVisibilityResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}/visibility",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Showtime Visibility
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.requestBody
   * @returns ShowtimeVisibilityPublic Successful Response
   * @throws ApiError
   */
  public static updateShowtimeVisibility(
    data: ShowtimesUpdateShowtimeVisibilityData,
  ): CancelablePromise<ShowtimesUpdateShowtimeVisibilityResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/showtimes/{showtime_id}/visibility",
      path: {
        showtime_id: data.showtimeId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Main Page Showtimes
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getMainPageShowtimes(
    data: ShowtimesGetMainPageShowtimesData = {},
  ): CancelablePromise<ShowtimesGetMainPageShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/",
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Search Users
   * @param data The data for the request.
   * @param data.query
   * @param data.offset
   * @param data.limit
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static searchUsers(
    data: UsersSearchUsersData,
  ): CancelablePromise<UsersSearchUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/search",
      query: {
        query: data.query,
        offset: data.offset,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User
   * Get a user by their ID.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static getUser(
    data: UsersGetUserData,
  ): CancelablePromise<UsersGetUserResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Selected Showtimes
   * @param data The data for the request.
   * @param data.userId
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getUserSelectedShowtimes(
    data: UsersGetUserSelectedShowtimesData,
  ): CancelablePromise<UsersGetUserSelectedShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}/showtimes",
      path: {
        user_id: data.userId,
      },
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }

  /**
   * Override Tmdb Cache Entry
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TmdbCacheOverrideResponse Successful Response
   * @throws ApiError
   */
  public static overrideTmdbCacheEntry(
    data: UtilsOverrideTmdbCacheEntryData,
  ): CancelablePromise<UtilsOverrideTmdbCacheEntryResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/tmdb-cache/override/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}
