// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  CinemasGetAllCinemasResponse,
  FriendsSendFriendRequestData,
  FriendsSendFriendRequestResponse,
  FriendsAcceptFriendRequestData,
  FriendsAcceptFriendRequestResponse,
  FriendsDeclineFriendRequestData,
  FriendsDeclineFriendRequestResponse,
  FriendsCancelFriendRequestData,
  FriendsCancelFriendRequestResponse,
  FriendsRemoveFriendData,
  FriendsRemoveFriendResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginRefreshAccessTokenData,
  LoginRefreshAccessTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  MeGetCurrentUserResponse,
  MeDeleteUserMeResponse,
  MeUpdateUserMeData,
  MeUpdateUserMeResponse,
  MeGetFilterPresetsData,
  MeGetFilterPresetsResponse,
  MeCreateFilterPresetData,
  MeCreateFilterPresetResponse,
  MeGetFavoriteFilterPresetData,
  MeGetFavoriteFilterPresetResponse,
  MeClearFavoriteFilterPresetData,
  MeClearFavoriteFilterPresetResponse,
  MeSetFavoriteFilterPresetData,
  MeSetFavoriteFilterPresetResponse,
  MeDeleteFilterPresetData,
  MeDeleteFilterPresetResponse,
  MeGetSavedPresetsData,
  MeGetSavedPresetsResponse,
  MeCreateSavedPresetData,
  MeCreateSavedPresetResponse,
  MeGetFavoriteSavedPresetData,
  MeGetFavoriteSavedPresetResponse,
  MeClearFavoriteSavedPresetData,
  MeClearFavoriteSavedPresetResponse,
  MeSetFavoriteSavedPresetData,
  MeSetFavoriteSavedPresetResponse,
  MeDeleteSavedPresetData,
  MeDeleteSavedPresetResponse,
  MeGetCinemaPresetsResponse,
  MeCreateCinemaPresetData,
  MeCreateCinemaPresetResponse,
  MeGetFavoriteCinemaPresetResponse,
  MeClearFavoriteCinemaPresetResponse,
  MeSetFavoriteCinemaPresetData,
  MeSetFavoriteCinemaPresetResponse,
  MeDeleteCinemaPresetData,
  MeDeleteCinemaPresetResponse,
  MeGetFriendGroupsResponse,
  MeCreateFriendGroupData,
  MeCreateFriendGroupResponse,
  MeGetFavoriteFriendGroupResponse,
  MeClearFavoriteFriendGroupResponse,
  MeSetFavoriteFriendGroupData,
  MeSetFavoriteFriendGroupResponse,
  MeDeleteFriendGroupData,
  MeDeleteFriendGroupResponse,
  MeUpdatePasswordMeData,
  MeUpdatePasswordMeResponse,
  MeCountMyShowtimesData,
  MeCountMyShowtimesResponse,
  MeGetMyShowtimesData,
  MeGetMyShowtimesResponse,
  MeGetMyAgendaData,
  MeGetMyAgendaResponse,
  MeGetMyShowtimePingsData,
  MeGetMyShowtimePingsResponse,
  MeGetMyUnseenShowtimePingCountResponse,
  MeMarkMyShowtimePingsSeenResponse,
  MeDeleteMyShowtimePingData,
  MeDeleteMyShowtimePingResponse,
  MeDismissMyShowtimePingData,
  MeDismissMyShowtimePingResponse,
  MeGetMyNotificationsData,
  MeGetMyNotificationsResponse,
  MeGetMyUnseenNotificationCountResponse,
  MeMarkMyNotificationsSeenResponse,
  MeDismissMyNotificationData,
  MeDismissMyNotificationResponse,
  MeSyncWatchlistResponse,
  MeSyncWatchedResponse,
  MeGetLetterboxdListsResponse,
  MeAddLetterboxdListData,
  MeAddLetterboxdListResponse,
  MeSyncLetterboxdListData,
  MeSyncLetterboxdListResponse,
  MeRemoveLetterboxdListData,
  MeRemoveLetterboxdListResponse,
  MeGetFriendsResponse,
  MeGetSentFriendRequestsResponse,
  MeGetReceivedFriendRequestsResponse,
  MeGetCinemaSelectionsResponse,
  MeSetCinemaSelectionsData,
  MeSetCinemaSelectionsResponse,
  MeRegisterPushTokenData,
  MeRegisterPushTokenResponse,
  MeDeletePushTokenData,
  MeDeletePushTokenResponse,
  MoviesCountMoviesData,
  MoviesCountMoviesResponse,
  MoviesReadMoviesData,
  MoviesReadMoviesResponse,
  MoviesReadMovieShowtimesData,
  MoviesReadMovieShowtimesResponse,
  MoviesReadMovieData,
  MoviesReadMovieResponse,
  ShowtimesUpdateShowtimeSelectionData,
  ShowtimesUpdateShowtimeSelectionResponse,
  ShowtimesPingFriendForShowtimeData,
  ShowtimesPingFriendForShowtimeResponse,
  ShowtimesUninviteFriendFromShowtimeData,
  ShowtimesUninviteFriendFromShowtimeResponse,
  ShowtimesPingFriendGroupForShowtimeData,
  ShowtimesPingFriendGroupForShowtimeResponse,
  ShowtimesReceivePingFromLinkData,
  ShowtimesReceivePingFromLinkResponse,
  ShowtimesGetPingedFriendIdsForShowtimeData,
  ShowtimesGetPingedFriendIdsForShowtimeResponse,
  ShowtimesGetSentPingsForShowtimeData,
  ShowtimesGetSentPingsForShowtimeResponse,
  ShowtimesGetShowtimeVisibilityBatchData,
  ShowtimesGetShowtimeVisibilityBatchResponse,
  ShowtimesGetShowtimeVisibilityData,
  ShowtimesGetShowtimeVisibilityResponse,
  ShowtimesUpdateShowtimeVisibilityData,
  ShowtimesUpdateShowtimeVisibilityResponse,
  ShowtimesCountMainPageShowtimesData,
  ShowtimesCountMainPageShowtimesResponse,
  ShowtimesGetMainPageShowtimesData,
  ShowtimesGetMainPageShowtimesResponse,
  ShowtimesGetShowtimeByIdData,
  ShowtimesGetShowtimeByIdResponse,
  UsersSearchUsersData,
  UsersSearchUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersGetUserData,
  UsersGetUserResponse,
  UsersGetUserSelectedShowtimesData,
  UsersGetUserSelectedShowtimesResponse,
  UtilsHealthCheckResponse,
  UtilsOverrideTmdbCacheEntryData,
  UtilsOverrideTmdbCacheEntryResponse,
} from "./types.gen"

export class CinemasService {
  /**
   * Get All Cinemas
   * @returns CinemaPublic Successful Response
   * @throws ApiError
   */
  public static getAllCinemas(): CancelablePromise<CinemasGetAllCinemasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/cinemas/",
    })
  }
}

export class FriendsService {
  /**
   * Send Friend Request
   * @param data The data for the request.
   * @param data.receiverId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static sendFriendRequest(
    data: FriendsSendFriendRequestData,
  ): CancelablePromise<FriendsSendFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/request/{receiver_id}",
      path: {
        receiver_id: data.receiverId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Accept Friend Request
   * @param data The data for the request.
   * @param data.senderId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static acceptFriendRequest(
    data: FriendsAcceptFriendRequestData,
  ): CancelablePromise<FriendsAcceptFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/accept/{sender_id}",
      path: {
        sender_id: data.senderId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Decline Friend Request
   * @param data The data for the request.
   * @param data.senderId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static declineFriendRequest(
    data: FriendsDeclineFriendRequestData,
  ): CancelablePromise<FriendsDeclineFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/friends/decline/{sender_id}",
      path: {
        sender_id: data.senderId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Cancel Friend Request
   * @param data The data for the request.
   * @param data.receiverId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static cancelFriendRequest(
    data: FriendsCancelFriendRequestData,
  ): CancelablePromise<FriendsCancelFriendRequestResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/friends/cancel/{receiver_id}",
      path: {
        receiver_id: data.receiverId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remove Friend
   * @param data The data for the request.
   * @param data.friendId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static removeFriend(
    data: FriendsRemoveFriendData,
  ): CancelablePromise<FriendsRemoveFriendResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/friends/{friend_id}",
      path: {
        friend_id: data.friendId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * Authenticate a user and return a JWT access + refresh token pair.
   *
   * Uses OAuth2 password flow — credentials are submitted as form data.
   * The access token should be included in subsequent requests as:
   * Authorization: Bearer <access_token>
   * The refresh token is exchanged at POST /login/refresh-token when the access
   * token expires.
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Refresh Access Token
   * Exchange a valid refresh token for a fresh access + refresh token pair.
   *
   * The refresh token is rotated on every call (sliding window). Returns 401 if
   * the refresh token is missing, expired, tampered with, the wrong token type,
   * or the user no longer exists / is inactive.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static refreshAccessToken(
    data: LoginRefreshAccessTokenData,
  ): CancelablePromise<LoginRefreshAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/refresh-token",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password
   * Send a password reset email to the given address.
   *
   * Always returns 200 regardless of whether the email exists, to prevent
   * user enumeration attacks.
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset the user's password using a valid password reset token.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MeService {
  /**
   * Get Current User
   * @returns UserMe Successful Response
   * @throws ApiError
   */
  public static getCurrentUser(): CancelablePromise<MeGetCurrentUserResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/",
    })
  }

  /**
   * Delete User Me
   * Delete the authenticated user's own account. Superusers cannot delete themselves.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<MeDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/",
    })
  }

  /**
   * Update User Me
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserMe Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: MeUpdateUserMeData,
  ): CancelablePromise<MeUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/me/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Filter Presets
   * @param data The data for the request.
   * @param data.scope
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static getFilterPresets(
    data: MeGetFilterPresetsData,
  ): CancelablePromise<MeGetFilterPresetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/filter-presets",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Filter Preset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static createFilterPreset(
    data: MeCreateFilterPresetData,
  ): CancelablePromise<MeCreateFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/filter-presets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Filter Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteFilterPreset(
    data: MeGetFavoriteFilterPresetData,
  ): CancelablePromise<MeGetFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/filter-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Clear Favorite Filter Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteFilterPreset(
    data: MeClearFavoriteFilterPresetData,
  ): CancelablePromise<MeClearFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/filter-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Set Favorite Filter Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns FilterPresetPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteFilterPreset(
    data: MeSetFavoriteFilterPresetData,
  ): CancelablePromise<MeSetFavoriteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/filter-presets/{preset_id}/favorite",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Filter Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFilterPreset(
    data: MeDeleteFilterPresetData,
  ): CancelablePromise<MeDeleteFilterPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/filter-presets/{preset_id}",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Saved Presets
   * @param data The data for the request.
   * @param data.scope
   * @returns SavedPresetPublic Successful Response
   * @throws ApiError
   */
  public static getSavedPresets(
    data: MeGetSavedPresetsData,
  ): CancelablePromise<MeGetSavedPresetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/saved-presets",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Saved Preset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns SavedPresetPublic Successful Response
   * @throws ApiError
   */
  public static createSavedPreset(
    data: MeCreateSavedPresetData,
  ): CancelablePromise<MeCreateSavedPresetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/saved-presets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Saved Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteSavedPreset(
    data: MeGetFavoriteSavedPresetData,
  ): CancelablePromise<MeGetFavoriteSavedPresetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/saved-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Clear Favorite Saved Preset
   * @param data The data for the request.
   * @param data.scope
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteSavedPreset(
    data: MeClearFavoriteSavedPresetData,
  ): CancelablePromise<MeClearFavoriteSavedPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/saved-presets/favorite",
      query: {
        scope: data.scope,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Set Favorite Saved Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns SavedPresetPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteSavedPreset(
    data: MeSetFavoriteSavedPresetData,
  ): CancelablePromise<MeSetFavoriteSavedPresetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/saved-presets/{preset_id}/favorite",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Saved Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteSavedPreset(
    data: MeDeleteSavedPresetData,
  ): CancelablePromise<MeDeleteSavedPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/saved-presets/{preset_id}",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Cinema Presets
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static getCinemaPresets(): CancelablePromise<MeGetCinemaPresetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinema-presets",
    })
  }

  /**
   * Create Cinema Preset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static createCinemaPreset(
    data: MeCreateCinemaPresetData,
  ): CancelablePromise<MeCreateCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/cinema-presets",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Cinema Preset
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteCinemaPreset(): CancelablePromise<MeGetFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinema-presets/favorite",
    })
  }

  /**
   * Clear Favorite Cinema Preset
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteCinemaPreset(): CancelablePromise<MeClearFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/cinema-presets/favorite",
    })
  }

  /**
   * Set Favorite Cinema Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns CinemaPresetPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteCinemaPreset(
    data: MeSetFavoriteCinemaPresetData,
  ): CancelablePromise<MeSetFavoriteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/cinema-presets/{preset_id}/favorite",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Cinema Preset
   * @param data The data for the request.
   * @param data.presetId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCinemaPreset(
    data: MeDeleteCinemaPresetData,
  ): CancelablePromise<MeDeleteCinemaPresetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/cinema-presets/{preset_id}",
      path: {
        preset_id: data.presetId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Friend Groups
   * @returns FriendGroupPublic Successful Response
   * @throws ApiError
   */
  public static getFriendGroups(): CancelablePromise<MeGetFriendGroupsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/friend-groups",
    })
  }

  /**
   * Create Friend Group
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FriendGroupPublic Successful Response
   * @throws ApiError
   */
  public static createFriendGroup(
    data: MeCreateFriendGroupData,
  ): CancelablePromise<MeCreateFriendGroupResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/friend-groups",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Favorite Friend Group
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getFavoriteFriendGroup(): CancelablePromise<MeGetFavoriteFriendGroupResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/friend-groups/favorite",
    })
  }

  /**
   * Clear Favorite Friend Group
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static clearFavoriteFriendGroup(): CancelablePromise<MeClearFavoriteFriendGroupResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/friend-groups/favorite",
    })
  }

  /**
   * Set Favorite Friend Group
   * @param data The data for the request.
   * @param data.groupId
   * @returns FriendGroupPublic Successful Response
   * @throws ApiError
   */
  public static setFavoriteFriendGroup(
    data: MeSetFavoriteFriendGroupData,
  ): CancelablePromise<MeSetFavoriteFriendGroupResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/friend-groups/{group_id}/favorite",
      path: {
        group_id: data.groupId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Friend Group
   * @param data The data for the request.
   * @param data.groupId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFriendGroup(
    data: MeDeleteFriendGroupData,
  ): CancelablePromise<MeDeleteFriendGroupResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/friend-groups/{group_id}",
      path: {
        group_id: data.groupId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Change the authenticated user's password. Requires the current password to be provided.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: MeUpdatePasswordMeData,
  ): CancelablePromise<MeUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Count My Showtimes
   * @param data The data for the request.
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns number Successful Response
   * @throws ApiError
   */
  public static countMyShowtimes(
    data: MeCountMyShowtimesData = {},
  ): CancelablePromise<MeCountMyShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/showtimes/count",
      query: {
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Showtimes
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getMyShowtimes(
    data: MeGetMyShowtimesData = {},
  ): CancelablePromise<MeGetMyShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/showtimes",
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Agenda
   * @param data The data for the request.
   * @param data.includeInterested
   * @param data.includeInvited
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.limit
   * @param data.offset
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getMyAgenda(
    data: MeGetMyAgendaData = {},
  ): CancelablePromise<MeGetMyAgendaResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/agenda",
      query: {
        include_interested: data.includeInterested,
        include_invited: data.includeInvited,
        snapshot_time: data.snapshotTime,
        limit: data.limit,
        offset: data.offset,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Showtime Pings
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.sortBy
   * @returns ShowtimePingPublic Successful Response
   * @throws ApiError
   */
  public static getMyShowtimePings(
    data: MeGetMyShowtimePingsData = {},
  ): CancelablePromise<MeGetMyShowtimePingsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/pings",
      query: {
        limit: data.limit,
        offset: data.offset,
        sort_by: data.sortBy,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Unseen Showtime Ping Count
   * @returns number Successful Response
   * @throws ApiError
   */
  public static getMyUnseenShowtimePingCount(): CancelablePromise<MeGetMyUnseenShowtimePingCountResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/pings/unseen-count",
    })
  }

  /**
   * Mark My Showtime Pings Seen
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static markMyShowtimePingsSeen(): CancelablePromise<MeMarkMyShowtimePingsSeenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/pings/mark-seen",
    })
  }

  /**
   * Delete My Showtime Ping
   * @param data The data for the request.
   * @param data.pingId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteMyShowtimePing(
    data: MeDeleteMyShowtimePingData,
  ): CancelablePromise<MeDeleteMyShowtimePingResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/pings/{ping_id}",
      path: {
        ping_id: data.pingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Dismiss My Showtime Ping
   * @param data The data for the request.
   * @param data.pingId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static dismissMyShowtimePing(
    data: MeDismissMyShowtimePingData,
  ): CancelablePromise<MeDismissMyShowtimePingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/pings/{ping_id}/dismiss",
      path: {
        ping_id: data.pingId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Notifications
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @returns NotificationFeedItem Successful Response
   * @throws ApiError
   */
  public static getMyNotifications(
    data: MeGetMyNotificationsData = {},
  ): CancelablePromise<MeGetMyNotificationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/notifications",
      query: {
        limit: data.limit,
        offset: data.offset,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get My Unseen Notification Count
   * @returns number Successful Response
   * @throws ApiError
   */
  public static getMyUnseenNotificationCount(): CancelablePromise<MeGetMyUnseenNotificationCountResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/notifications/unseen-count",
    })
  }

  /**
   * Mark My Notifications Seen
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static markMyNotificationsSeen(): CancelablePromise<MeMarkMyNotificationsSeenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/notifications/mark-seen",
    })
  }

  /**
   * Dismiss My Notification
   * @param data The data for the request.
   * @param data.notificationId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static dismissMyNotification(
    data: MeDismissMyNotificationData,
  ): CancelablePromise<MeDismissMyNotificationResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/notifications/{notification_id}",
      path: {
        notification_id: data.notificationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Sync Watchlist
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static syncWatchlist(): CancelablePromise<MeSyncWatchlistResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/watchlist",
    })
  }

  /**
   * Sync Watched
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static syncWatched(): CancelablePromise<MeSyncWatchedResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/watched",
    })
  }

  /**
   * Get Letterboxd Lists
   * @returns LetterboxdListPublic Successful Response
   * @throws ApiError
   */
  public static getLetterboxdLists(): CancelablePromise<MeGetLetterboxdListsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/letterboxd-lists",
    })
  }

  /**
   * Add Letterboxd List
   * @param data The data for the request.
   * @param data.requestBody
   * @returns LetterboxdListPublic Successful Response
   * @throws ApiError
   */
  public static addLetterboxdList(
    data: MeAddLetterboxdListData,
  ): CancelablePromise<MeAddLetterboxdListResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/letterboxd-lists",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Sync Letterboxd List
   * @param data The data for the request.
   * @param data.listId
   * @returns LetterboxdListPublic Successful Response
   * @throws ApiError
   */
  public static syncLetterboxdList(
    data: MeSyncLetterboxdListData,
  ): CancelablePromise<MeSyncLetterboxdListResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/me/letterboxd-lists/{list_id}/sync",
      path: {
        list_id: data.listId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remove Letterboxd List
   * @param data The data for the request.
   * @param data.listId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static removeLetterboxdList(
    data: MeRemoveLetterboxdListData,
  ): CancelablePromise<MeRemoveLetterboxdListResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/letterboxd-lists/{list_id}",
      path: {
        list_id: data.listId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Friends
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getFriends(): CancelablePromise<MeGetFriendsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/friends",
    })
  }

  /**
   * Get Sent Friend Requests
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getSentFriendRequests(): CancelablePromise<MeGetSentFriendRequestsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/requests/sent",
    })
  }

  /**
   * Get Received Friend Requests
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static getReceivedFriendRequests(): CancelablePromise<MeGetReceivedFriendRequestsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/requests/received",
    })
  }

  /**
   * Get Cinema Selections
   * @returns number Successful Response
   * @throws ApiError
   */
  public static getCinemaSelections(): CancelablePromise<MeGetCinemaSelectionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/cinemas",
    })
  }

  /**
   * Set Cinema Selections
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static setCinemaSelections(
    data: MeSetCinemaSelectionsData,
  ): CancelablePromise<MeSetCinemaSelectionsResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/cinemas",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register Push Token
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static registerPushToken(
    data: MeRegisterPushTokenData,
  ): CancelablePromise<MeRegisterPushTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/me/push-tokens",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Push Token
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deletePushToken(
    data: MeDeletePushTokenData,
  ): CancelablePromise<MeDeletePushTokenResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/me/push-tokens",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MoviesService {
  /**
   * Count Movies
   * @param data The data for the request.
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns number Successful Response
   * @throws ApiError
   */
  public static countMovies(
    data: MoviesCountMoviesData = {},
  ): CancelablePromise<MoviesCountMoviesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/count",
      query: {
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Movies
   * @param data The data for the request.
   * @param data.offset
   * @param data.limit
   * @param data.showtimeLimit
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns MovieSummaryLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovies(
    data: MoviesReadMoviesData = {},
  ): CancelablePromise<MoviesReadMoviesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/",
      query: {
        offset: data.offset,
        limit: data.limit,
        showtime_limit: data.showtimeLimit,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Movie Showtimes
   * @param data The data for the request.
   * @param data.id
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns ShowtimeInMovieLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovieShowtimes(
    data: MoviesReadMovieShowtimesData,
  ): CancelablePromise<MoviesReadMovieShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/{id}/showtimes",
      path: {
        id: data.id,
      },
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Movie
   * @param data The data for the request.
   * @param data.id
   * @param data.showtimeLimit
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns MovieLoggedIn Successful Response
   * @throws ApiError
   */
  public static readMovie(
    data: MoviesReadMovieData,
  ): CancelablePromise<MoviesReadMovieResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/movies/{id}",
      path: {
        id: data.id,
      },
      query: {
        showtime_limit: data.showtimeLimit,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ShowtimesService {
  /**
   * Update Showtime Selection
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.requestBody
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static updateShowtimeSelection(
    data: ShowtimesUpdateShowtimeSelectionData,
  ): CancelablePromise<ShowtimesUpdateShowtimeSelectionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/showtimes/selection/{showtime_id}",
      path: {
        showtime_id: data.showtimeId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Ping Friend For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.friendId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static pingFriendForShowtime(
    data: ShowtimesPingFriendForShowtimeData,
  ): CancelablePromise<ShowtimesPingFriendForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/showtimes/{showtime_id}/ping/{friend_id}",
      path: {
        showtime_id: data.showtimeId,
        friend_id: data.friendId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Uninvite Friend From Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.friendId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static uninviteFriendFromShowtime(
    data: ShowtimesUninviteFriendFromShowtimeData,
  ): CancelablePromise<ShowtimesUninviteFriendFromShowtimeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/showtimes/{showtime_id}/ping/{friend_id}",
      path: {
        showtime_id: data.showtimeId,
        friend_id: data.friendId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Ping Friend Group For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.groupId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static pingFriendGroupForShowtime(
    data: ShowtimesPingFriendGroupForShowtimeData,
  ): CancelablePromise<ShowtimesPingFriendGroupForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/showtimes/{showtime_id}/ping-group/{group_id}",
      path: {
        showtime_id: data.showtimeId,
        group_id: data.groupId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Receive Ping From Link
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.senderIdentifier
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static receivePingFromLink(
    data: ShowtimesReceivePingFromLinkData,
  ): CancelablePromise<ShowtimesReceivePingFromLinkResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/showtimes/{showtime_id}/ping-link/{sender_identifier}",
      path: {
        showtime_id: data.showtimeId,
        sender_identifier: data.senderIdentifier,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Pinged Friend Ids For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns string Successful Response
   * @throws ApiError
   */
  public static getPingedFriendIdsForShowtime(
    data: ShowtimesGetPingedFriendIdsForShowtimeData,
  ): CancelablePromise<ShowtimesGetPingedFriendIdsForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}/pinged-friends",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Sent Pings For Showtime
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns SentShowtimePingPublic Successful Response
   * @throws ApiError
   */
  public static getSentPingsForShowtime(
    data: ShowtimesGetSentPingsForShowtimeData,
  ): CancelablePromise<ShowtimesGetSentPingsForShowtimeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}/sent-pings",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Showtime Visibility Batch
   * @param data The data for the request.
   * @param data.showtimeIds
   * @returns ShowtimeVisibilityPublic Successful Response
   * @throws ApiError
   */
  public static getShowtimeVisibilityBatch(
    data: ShowtimesGetShowtimeVisibilityBatchData = {},
  ): CancelablePromise<ShowtimesGetShowtimeVisibilityBatchResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/visibility/batch",
      query: {
        showtime_ids: data.showtimeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Showtime Visibility
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns ShowtimeVisibilityPublic Successful Response
   * @throws ApiError
   */
  public static getShowtimeVisibility(
    data: ShowtimesGetShowtimeVisibilityData,
  ): CancelablePromise<ShowtimesGetShowtimeVisibilityResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}/visibility",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Showtime Visibility
   * @param data The data for the request.
   * @param data.showtimeId
   * @param data.requestBody
   * @returns ShowtimeVisibilityPublic Successful Response
   * @throws ApiError
   */
  public static updateShowtimeVisibility(
    data: ShowtimesUpdateShowtimeVisibilityData,
  ): CancelablePromise<ShowtimesUpdateShowtimeVisibilityResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/showtimes/{showtime_id}/visibility",
      path: {
        showtime_id: data.showtimeId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Count Main Page Showtimes
   * @param data The data for the request.
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns number Successful Response
   * @throws ApiError
   */
  public static countMainPageShowtimes(
    data: ShowtimesCountMainPageShowtimesData = {},
  ): CancelablePromise<ShowtimesCountMainPageShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/count",
      query: {
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Main Page Showtimes
   * @param data The data for the request.
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getMainPageShowtimes(
    data: ShowtimesGetMainPageShowtimesData = {},
  ): CancelablePromise<ShowtimesGetMainPageShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/",
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Showtime By Id
   * @param data The data for the request.
   * @param data.showtimeId
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getShowtimeById(
    data: ShowtimesGetShowtimeByIdData,
  ): CancelablePromise<ShowtimesGetShowtimeByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/showtimes/{showtime_id}",
      path: {
        showtime_id: data.showtimeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Search Users
   * @param data The data for the request.
   * @param data.query
   * @param data.offset
   * @param data.limit
   * @returns UserWithFriendStatus Successful Response
   * @throws ApiError
   */
  public static searchUsers(
    data: UsersSearchUsersData,
  ): CancelablePromise<UsersSearchUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/search",
      query: {
        query: data.query,
        offset: data.offset,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User
   * Get a user by their ID.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static getUser(
    data: UsersGetUserData,
  ): CancelablePromise<UsersGetUserResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Selected Showtimes
   * @param data The data for the request.
   * @param data.userId
   * @param data.limit
   * @param data.offset
   * @param data.query
   * @param data.snapshotTime Only show showtimes after this moment
   * @param data.watchlistOnly
   * @param data.hideWatched
   * @param data.selectedCinemaIds Filter showtimes to only these cinema IDs
   * @param data.days
   * @param data.timeRanges
   * @param data.timesOfDay Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   * @param data.selectedStatuses Filter by selection statuses (GOING/INTERESTED)
   * @param data.runtimeMin Minimum movie runtime in minutes
   * @param data.runtimeMax Maximum movie runtime in minutes
   * @returns ShowtimeLoggedIn Successful Response
   * @throws ApiError
   */
  public static getUserSelectedShowtimes(
    data: UsersGetUserSelectedShowtimesData,
  ): CancelablePromise<UsersGetUserSelectedShowtimesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}/showtimes",
      path: {
        user_id: data.userId,
      },
      query: {
        limit: data.limit,
        offset: data.offset,
        query: data.query,
        snapshot_time: data.snapshotTime,
        watchlist_only: data.watchlistOnly,
        hide_watched: data.hideWatched,
        selected_cinema_ids: data.selectedCinemaIds,
        days: data.days,
        time_ranges: data.timeRanges,
        times_of_day: data.timesOfDay,
        selected_statuses: data.selectedStatuses,
        runtime_min: data.runtimeMin,
        runtime_max: data.runtimeMax,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }

  /**
   * Override Tmdb Cache Entry
   * @param data The data for the request.
   * @param data.requestBody
   * @returns TmdbCacheOverrideResponse Successful Response
   * @throws ApiError
   */
  public static overrideTmdbCacheEntry(
    data: UtilsOverrideTmdbCacheEntryData,
  ): CancelablePromise<UtilsOverrideTmdbCacheEntryResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/tmdb-cache/override/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}
