// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CinemaPresetCreate = {
  name: string
  cinema_ids?: Array<number>
  is_favorite?: boolean | null
}

export type CinemaPresetPublic = {
  id: string
  name: string
  cinema_ids: Array<number>
  is_favorite: boolean
  created_at: string
  updated_at: string
}

export type CinemaPublic = {
  /**
   * Name of the cinema
   */
  name: string
  cineville: boolean
  badge_bg_color: string
  url: string
  id: number
  city: CityPublic
  test?: number
}

export type CityPublic = {
  /**
   * Name of the city
   */
  name: string
  /**
   * ID of the city
   */
  id: number
}

export type FilterPresetCreate = {
  name: string
  scope: FilterPresetScope
  filters: FilterPresetFilters
  is_favorite?: boolean | null
}

export type FilterPresetFilters = {
  selected_showtime_filter?: "all" | "interested" | "going" | null
  watchlist_only?: boolean
  days?: Array<string> | null
  time_ranges?: Array<string> | null
}

export type FilterPresetPublic = {
  id: string
  name: string
  scope: FilterPresetScope
  is_default: boolean
  is_favorite: boolean
  filters: FilterPresetFilters
  created_at: string
  updated_at: string
}

export type FilterPresetScope = "SHOWTIMES" | "MOVIES"

export type GoingStatus = "GOING" | "NOT_GOING" | "INTERESTED"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type MovieLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  release_year?: number | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
}

export type MovieSummaryLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  release_year?: number | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
  cinemas: Array<CinemaPublic>
  last_showtime_datetime: string | null
  total_showtimes: number
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PushTokenRegister = {
  token: string
  platform?: "ios" | "android" | "web" | null
}

export type ShowtimeInMovieLoggedIn = {
  datetime: string
  ticket_link?: string | null
  id: number
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type ShowtimeLoggedIn = {
  datetime: string
  ticket_link?: string | null
  id: number
  movie: MovieSummaryLoggedIn
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type ShowtimePingPublic = {
  id: number
  showtime_id: number
  movie_id: number
  movie_title: string
  movie_poster_link: string | null
  cinema_name: string
  datetime: string
  ticket_link: string | null
  sender: UserPublic
  created_at: string
  seen_at: string | null
}

export type ShowtimeSelectionUpdate = {
  going_status: GoingStatus
}

export type TimeOfDay = "MORNING" | "AFTERNOON" | "EVENING" | "NIGHT"

export type TmdbCacheOverrideRequest = {
  title_query: string
  director_names?: Array<string>
  actor_name?: string | null
  year?: number | null
  tmdb_id?: number | null
}

export type TmdbCacheOverrideResponse = {
  lookup_hash: string
  lookup_payload: string
  tmdb_id: number | null
}

export type Token = {
  access_token: string
  /**
   * Type of the token, usually 'bearer'
   */
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserMe = {
  id: string
  is_active: boolean
  display_name: string | null
  email: string
  is_superuser: boolean
  notify_on_friend_showtime_match: boolean
  notify_on_friend_requests: boolean
  notify_on_showtime_ping: boolean
  notify_on_interest_reminder: boolean
  letterboxd_username: string | null
}

export type UserPublic = {
  id: string
  is_active: boolean
  display_name: string | null
}

export type UserRegister = {
  email: string
  password: string
  display_name?: string | null
}

export type UserUpdate = {
  display_name?: string | null
  email?: string | null
  letterboxd_username?: string | null
  notify_on_friend_showtime_match?: boolean | null
  notify_on_friend_requests?: boolean | null
  notify_on_showtime_ping?: boolean | null
  notify_on_interest_reminder?: boolean | null
  password?: string | null
}

export type UserWithFriendStatus = {
  id: string
  is_active: boolean
  display_name: string | null
  is_friend: boolean
  sent_request: boolean
  received_request: boolean
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CinemasGetAllCinemasResponse = Array<CinemaPublic>

export type FriendsSendFriendRequestData = {
  receiverId: string
}

export type FriendsSendFriendRequestResponse = Message

export type FriendsAcceptFriendRequestData = {
  senderId: string
}

export type FriendsAcceptFriendRequestResponse = Message

export type FriendsDeclineFriendRequestData = {
  senderId: string
}

export type FriendsDeclineFriendRequestResponse = Message

export type FriendsCancelFriendRequestData = {
  receiverId: string
}

export type FriendsCancelFriendRequestResponse = Message

export type FriendsRemoveFriendData = {
  friendId: string
}

export type FriendsRemoveFriendResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MeGetCurrentUserResponse = UserMe

export type MeDeleteUserMeResponse = Message

export type MeUpdateUserMeData = {
  requestBody: UserUpdate
}

export type MeUpdateUserMeResponse = UserMe

export type MeGetFilterPresetsData = {
  scope: FilterPresetScope
}

export type MeGetFilterPresetsResponse = Array<FilterPresetPublic>

export type MeSaveFilterPresetData = {
  requestBody: FilterPresetCreate
}

export type MeSaveFilterPresetResponse = FilterPresetPublic

export type MeGetFavoriteFilterPresetData = {
  scope: FilterPresetScope
}

export type MeGetFavoriteFilterPresetResponse = FilterPresetPublic | null

export type MeClearFavoriteFilterPresetData = {
  scope: FilterPresetScope
}

export type MeClearFavoriteFilterPresetResponse = Message

export type MeSetFavoriteFilterPresetData = {
  presetId: string
}

export type MeSetFavoriteFilterPresetResponse = FilterPresetPublic

export type MeDeleteFilterPresetData = {
  presetId: string
}

export type MeDeleteFilterPresetResponse = Message

export type MeGetCinemaPresetsResponse = Array<CinemaPresetPublic>

export type MeSaveCinemaPresetData = {
  requestBody: CinemaPresetCreate
}

export type MeSaveCinemaPresetResponse = CinemaPresetPublic

export type MeGetFavoriteCinemaPresetResponse = CinemaPresetPublic | null

export type MeClearFavoriteCinemaPresetResponse = Message

export type MeSetFavoriteCinemaPresetData = {
  presetId: string
}

export type MeSetFavoriteCinemaPresetResponse = CinemaPresetPublic

export type MeDeleteCinemaPresetData = {
  presetId: string
}

export type MeDeleteCinemaPresetResponse = Message

export type MeUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type MeUpdatePasswordMeResponse = Message

export type MeGetMyShowtimesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type MeGetMyShowtimesResponse = Array<ShowtimeLoggedIn>

export type MeGetMyShowtimePingsData = {
  limit?: number
  offset?: number
}

export type MeGetMyShowtimePingsResponse = Array<ShowtimePingPublic>

export type MeGetMyUnseenShowtimePingCountResponse = number

export type MeMarkMyShowtimePingsSeenResponse = Message

export type MeSyncWatchlistResponse = Message

export type MeGetFriendsResponse = Array<UserWithFriendStatus>

export type MeGetSentFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetReceivedFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetCinemaSelectionsResponse = Array<number>

export type MeSetCinemaSelectionsData = {
  requestBody: Array<number>
}

export type MeSetCinemaSelectionsResponse = Message

export type MeRegisterPushTokenData = {
  requestBody: PushTokenRegister
}

export type MeRegisterPushTokenResponse = Message

export type MoviesReadMoviesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type MoviesReadMoviesResponse = Array<MovieSummaryLoggedIn>

export type MoviesReadMovieShowtimesData = {
  days?: Array<string> | null
  id: number
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type MoviesReadMovieShowtimesResponse = Array<ShowtimeInMovieLoggedIn>

export type MoviesReadMovieData = {
  days?: Array<string> | null
  id: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type MoviesReadMovieResponse = MovieLoggedIn

export type ShowtimesUpdateShowtimeSelectionData = {
  days?: Array<string> | null
  query?: string | null
  requestBody: ShowtimeSelectionUpdate
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeId: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type ShowtimesUpdateShowtimeSelectionResponse = ShowtimeLoggedIn

export type ShowtimesPingFriendForShowtimeData = {
  friendId: string
  showtimeId: number
}

export type ShowtimesPingFriendForShowtimeResponse = Message

export type ShowtimesGetPingedFriendIdsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetPingedFriendIdsForShowtimeResponse = Array<string>

export type ShowtimesGetMainPageShowtimesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchlistOnly?: boolean
}

export type ShowtimesGetMainPageShowtimesResponse = Array<ShowtimeLoggedIn>

export type UsersSearchUsersData = {
  limit?: number
  offset?: number
  query: string
}

export type UsersSearchUsersResponse = Array<UserWithFriendStatus>

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = UserPublic

export type UsersGetUserSelectedShowtimesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  userId: string
  watchlistOnly?: boolean
}

export type UsersGetUserSelectedShowtimesResponse = Array<ShowtimeLoggedIn>

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type UtilsOverrideTmdbCacheEntryData = {
  requestBody: TmdbCacheOverrideRequest
}

export type UtilsOverrideTmdbCacheEntryResponse = TmdbCacheOverrideResponse
