// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CinemaPresetCreate = {
  name: string
  cinema_ids?: Array<number>
  is_favorite?: boolean | null
}

export type CinemaPresetPublic = {
  id: string
  name: string
  is_default: boolean
  cinema_ids: Array<number>
  is_favorite: boolean
  created_at: string
  updated_at: string
}

export type CinemaPublic = {
  /**
   * Name of the cinema
   */
  name: string
  cineville: boolean
  badge_bg_color: string
  url: string
  seating?: CinemaSeatingPreset
  id: number
  city: CityPublic
  test?: number
}

/**
 * The seat labelling format used by a cinema.
 *
 * The value encodes the format as "{row_type}-{seat_type}". For assigned-seating
 * presets, the type is either "number" (1-2 digits) or "letter" (a single letter).
 *
 * Values:
 * - unknown:        Row and seat can be a letter or 1-2 digits (flexible default).
 * - free:           No assigned seating — no row/seat input allowed.
 * - number-number:  Row is 1-2 digits, seat is 1-2 digits. E.g. row=3, seat=12.
 * - letter-number:  Row is a letter, seat is 1-2 digits. E.g. row=B, seat=12.
 * - number-letter:  Row is 1-2 digits, seat is a letter. E.g. row=3, seat=C.
 * - letter-letter:  Row is a letter, seat is a letter. E.g. row=B, seat=C.
 */
export type CinemaSeatingPreset =
  | "unknown"
  | "free"
  | "number-number"
  | "letter-number"
  | "number-letter"
  | "letter-letter"

export type CityPublic = {
  /**
   * Name of the city
   */
  name: string
  /**
   * ID of the city
   */
  id: number
}

/**
 * A friend who was invited by the same person who invited you.
 *
 * `inviter` is whichever of your active inviters sent that friend their
 * invite — used to attribute the friend in the "Invited" list ("Invited by
 * <inviter>").
 */
export type CoInvitedFriendPublic = {
  friend: UserPublic
  inviter: UserPublic
}

export type FriendStatusSharingUpdate = {
  shares_status: boolean
}

/**
 * Whether a user intends to attend a showtime.
 *
 * Stored on ShowtimeSelection rows and used in visibility calculations.
 */
export type GoingStatus = "GOING" | "NOT_GOING" | "INTERESTED"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Languages selectable in the language filter.
 *
 * Values are ISO-639-1 codes matching ``Movie.original_language`` and the
 * codes found in ``Showtime.subtitles``.
 */
export type Language = "nl" | "en"

export type LetterboxdListCreate = {
  url: string
}

export type LetterboxdListPublic = {
  id: string
  owner: string
  list_slug: string
  title: string | null
  url: string
  is_curated: boolean
  last_updated_on_letterboxd: string | null
  last_synced: string | null
  film_count: number
}

export type Message = {
  message: string
}

export type MovieInShowtime = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
}

export type MovieLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
  friends_watchlisted?: Array<UserPublic>
  friends_watched?: Array<UserPublic>
}

export type MovieSummaryLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
  cinemas: Array<CinemaPublic>
  last_showtime_datetime: string | null
  total_showtimes: number
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * The delivery mechanism for a notification sent to a user.
 */
export type NotificationChannel = "push" | "email"

/**
 * One merged, time-sorted entry in the notification centre.
 *
 * The three sources (the ``notification`` table, received ``ShowtimePing``
 * rows, received ``FriendRequest`` rows) are normalised into this shape so the
 * client renders a single feed. ``source`` + ``id`` identify the underlying
 * row for actions.
 */
export type NotificationFeedItem = {
  source: "notification" | "ping" | "friend_request"
  id: string
  type:
    | "friend_showtime_match"
    | "showtime_invite"
    | "invite_response"
    | "friend_request_received"
    | "friend_request_accepted"
  created_at: string
  seen_at: string | null
  actor: UserPublic | null
  showtime: ShowtimeLoggedIn | null
}

export type source = "notification" | "ping" | "friend_request"

export type type =
  | "friend_showtime_match"
  | "showtime_invite"
  | "invite_response"
  | "friend_request_received"
  | "friend_request_accepted"

export type PushTokenDelete = {
  token: string
}

export type PushTokenRegister = {
  token: string
  platform?: "ios" | "android" | "web" | null
}

export type RefreshTokenRequest = {
  refresh_token: string
}

export type SavedPresetCreate = {
  name: string
  untouched_fields?: Array<string>
  filters: SavedPresetFilters
  cinema_ids?: Array<number> | null
  is_favorite?: boolean | null
}

export type SavedPresetFilters = {
  selected_showtime_filter?: "all" | "interested" | "going" | null
  showtime_audience?: "including-friends" | "only-you"
  watchlist_only?: boolean
  watchlist_exclude?: boolean
  hide_watched?: boolean
  watched_only?: boolean
  selected_list_ids?: Array<string> | null
  exclude_list_ids?: Array<string> | null
  days?: Array<string> | null
  time_ranges?: Array<string> | null
  runtime_ranges?: Array<string> | null
  group_by_movie?: boolean | null
  selected_languages?: Array<Language> | null
}

export type showtime_audience = "including-friends" | "only-you"

export type SavedPresetPublic = {
  id: string
  name: string
  is_favorite: boolean
  untouched_fields: Array<string>
  filters: SavedPresetFilters
  cinema_ids: Array<number> | null
  created_at: string
  updated_at: string
}

/**
 * Which attribute the movie search ``query`` is matched against.
 *
 * TITLE also matches ``original_title``; the others match arrays/related
 * tables rather than a single Movie column — see ``apply_search_filter``.
 */
export type SearchField = "title" | "director" | "actor" | "cinema" | "friend"

export type SentShowtimePingPublic = {
  id: number
  receiver_id: string
  receiver_name: string
  created_at: string
  seen_at: string | null
  dismissed_at: string | null
}

export type ShowtimeInMovieLoggedIn = {
  datetime: string
  end_datetime?: string | null
  ticket_link?: string | null
  subtitles?: Array<string> | null
  id: number
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  invited_by?: Array<UserPublic>
  invite_ping_ids?: Array<number>
  co_invited_friends?: Array<CoInvitedFriendPublic>
  pending_invited_friends?: Array<UserPublic>
}

export type ShowtimeLoggedIn = {
  datetime: string
  end_datetime?: string | null
  ticket_link?: string | null
  subtitles?: Array<string> | null
  id: number
  movie: MovieInShowtime
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  invited_by?: Array<UserPublic>
  invite_ping_ids?: Array<number>
  co_invited_friends?: Array<CoInvitedFriendPublic>
  pending_invited_friends?: Array<UserPublic>
  friends_watchlisted?: Array<UserPublic>
  friends_watched?: Array<UserPublic>
}

export type ShowtimePingPublic = {
  id: number
  showtime_id: number
  movie_id: number
  movie_title: string
  movie_poster_link: string | null
  cinema_name: string
  datetime: string
  ticket_link: string | null
  showtime: ShowtimeLoggedIn
  sender: UserPublic
  created_at: string
  seen_at: string | null
}

/**
 * Sort order options for the pings list endpoint.
 */
export type ShowtimePingSort = "ping_created_at" | "showtime_datetime"

export type ShowtimeSelectionUpdate = {
  going_status: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  visibility_mode?: VisibilityMode | null
}

export type ShowtimeVisibilityPublic = {
  showtime_id: number
  movie_id: number
  mode: VisibilityMode
}

export type ShowtimeVisibilityUpdate = {
  mode: VisibilityMode
}

/**
 * Coarse time-of-day bucket used for showtime filtering.
 *
 * Showtimes are bucketed into one of these values based on their start time,
 * allowing users to filter by "evening showings" etc. without specifying exact
 * hour ranges.
 */
export type TimeOfDay = "MORNING" | "AFTERNOON" | "EVENING" | "NIGHT"

export type TmdbCacheOverrideRequest = {
  title_query: string
  director_names?: Array<string>
  actor_name?: string | null
  year?: number | null
  duration_minutes?: number | null
  spoken_languages?: Array<string> | null
  tmdb_id?: number | null
  confidence?: number | null
}

export type TmdbCacheOverrideResponse = {
  lookup_hash: string
  lookup_payload: string
  tmdb_id: number | null
  confidence: number | null
}

export type Token = {
  access_token: string
  refresh_token: string
  /**
   * Type of the token, usually 'bearer'
   */
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserMe = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
  email: string
  is_superuser: boolean
  incognito_mode: boolean
  notify_on_friend_showtime_match: boolean
  notify_on_friend_requests: boolean
  notify_on_showtime_ping: boolean
  notify_on_invite_response: boolean
  notify_on_interest_reminder: boolean
  notify_channel_friend_showtime_match: NotificationChannel
  notify_channel_friend_requests: NotificationChannel
  notify_channel_showtime_ping: NotificationChannel
  notify_channel_invite_response: NotificationChannel
  notify_channel_interest_reminder: NotificationChannel
  letterboxd_username: string | null
  watchlist_last_synced?: string | null
  watched_last_synced?: string | null
}

export type UserPublic = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
}

export type UserRegister = {
  email: string
  password: string
  display_name?: string | null
}

export type UserUpdate = {
  display_name?: string | null
  email?: string | null
  letterboxd_username?: string | null
  incognito_mode?: boolean | null
  notify_on_friend_showtime_match?: boolean | null
  notify_on_friend_requests?: boolean | null
  notify_on_showtime_ping?: boolean | null
  notify_on_invite_response?: boolean | null
  notify_on_interest_reminder?: boolean | null
  notify_channel_friend_showtime_match?: NotificationChannel | null
  notify_channel_friend_requests?: NotificationChannel | null
  notify_channel_showtime_ping?: NotificationChannel | null
  notify_channel_invite_response?: NotificationChannel | null
  notify_channel_interest_reminder?: NotificationChannel | null
  password?: string | null
}

export type UserWithFriendStatus = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
  is_friend: boolean
  sent_request: boolean
  received_request: boolean
  shares_status?: boolean
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

/**
 * Who may see a user's attendance status for a showtime.
 *
 * Stored per showtime on ShowtimeVisibilitySetting.
 *
 * - ALL_FRIENDS: every friend you haven't opted out of sharing with.
 * - INVITED_ONLY: nobody by default.
 *
 * Regardless of the mode, your status is always visible to friends you
 * invited, friends who invited you, and friends co-invited by the same person
 * who invited you.
 */
export type VisibilityMode = "ALL_FRIENDS" | "INVITED_ONLY"

export type CinemasGetAllCinemasResponse = Array<CinemaPublic>

export type FriendsSendFriendRequestData = {
  receiverId: string
}

export type FriendsSendFriendRequestResponse = Message

export type FriendsAcceptFriendRequestData = {
  senderId: string
}

export type FriendsAcceptFriendRequestResponse = Message

export type FriendsDeclineFriendRequestData = {
  senderId: string
}

export type FriendsDeclineFriendRequestResponse = Message

export type FriendsCancelFriendRequestData = {
  receiverId: string
}

export type FriendsCancelFriendRequestResponse = Message

export type FriendsSetFriendStatusSharingData = {
  friendId: string
  requestBody: FriendStatusSharingUpdate
}

export type FriendsSetFriendStatusSharingResponse = Message

export type FriendsRemoveFriendData = {
  friendId: string
}

export type FriendsRemoveFriendResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginRefreshAccessTokenData = {
  requestBody: RefreshTokenRequest
}

export type LoginRefreshAccessTokenResponse = Token

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type MeGetCurrentUserResponse = UserMe

export type MeDeleteUserMeResponse = Message

export type MeUpdateUserMeData = {
  requestBody: UserUpdate
}

export type MeUpdateUserMeResponse = UserMe

export type MeGetSavedPresetsResponse = Array<SavedPresetPublic>

export type MeCreateSavedPresetData = {
  requestBody: SavedPresetCreate
}

export type MeCreateSavedPresetResponse = SavedPresetPublic

export type MeGetFavoriteSavedPresetResponse = SavedPresetPublic | null

export type MeClearFavoriteSavedPresetResponse = Message

export type MeSetFavoriteSavedPresetData = {
  presetId: string
}

export type MeSetFavoriteSavedPresetResponse = SavedPresetPublic

export type MeDeleteSavedPresetData = {
  presetId: string
}

export type MeDeleteSavedPresetResponse = Message

export type MeGetCinemaPresetsResponse = Array<CinemaPresetPublic>

export type MeCreateCinemaPresetData = {
  requestBody: CinemaPresetCreate
}

export type MeCreateCinemaPresetResponse = CinemaPresetPublic

export type MeGetFavoriteCinemaPresetResponse = CinemaPresetPublic | null

export type MeClearFavoriteCinemaPresetResponse = Message

export type MeSetFavoriteCinemaPresetData = {
  presetId: string
}

export type MeSetFavoriteCinemaPresetResponse = CinemaPresetPublic

export type MeDeleteCinemaPresetData = {
  presetId: string
}

export type MeDeleteCinemaPresetResponse = Message

export type MeUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type MeUpdatePasswordMeResponse = Message

export type MeCountMyShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MeCountMyShowtimesResponse = number

export type MeGetMyShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MeGetMyShowtimesResponse = Array<ShowtimeLoggedIn>

export type MeGetMyAgendaData = {
  includeInterested?: boolean
  includeInvited?: boolean
  limit?: number
  offset?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
}

export type MeGetMyAgendaResponse = Array<ShowtimeLoggedIn>

export type MeGetMyShowtimePingsData = {
  limit?: number
  offset?: number
  sortBy?: ShowtimePingSort
}

export type MeGetMyShowtimePingsResponse = Array<ShowtimePingPublic>

export type MeGetMyUnseenShowtimePingCountResponse = number

export type MeMarkMyShowtimePingsSeenResponse = Message

export type MeDeleteMyShowtimePingData = {
  pingId: number
}

export type MeDeleteMyShowtimePingResponse = Message

export type MeDismissMyShowtimePingData = {
  pingId: number
}

export type MeDismissMyShowtimePingResponse = Message

export type MeGetMyNotificationsData = {
  limit?: number
  offset?: number
}

export type MeGetMyNotificationsResponse = Array<NotificationFeedItem>

export type MeGetMyUnseenNotificationCountResponse = number

export type MeMarkMyNotificationsSeenResponse = Message

export type MeDismissMyNotificationData = {
  notificationId: number
}

export type MeDismissMyNotificationResponse = Message

export type MeSyncWatchlistResponse = Message

export type MeSyncWatchedResponse = Message

export type MeGetLetterboxdListsResponse = Array<LetterboxdListPublic>

export type MeAddLetterboxdListData = {
  requestBody: LetterboxdListCreate
}

export type MeAddLetterboxdListResponse = LetterboxdListPublic

export type MeSyncLetterboxdListData = {
  listId: string
}

export type MeSyncLetterboxdListResponse = LetterboxdListPublic

export type MeRemoveLetterboxdListData = {
  listId: string
}

export type MeRemoveLetterboxdListResponse = Message

export type MeGetFriendsResponse = Array<UserWithFriendStatus>

export type MeGetSentFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetReceivedFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetCinemaSelectionsResponse = Array<number>

export type MeSetCinemaSelectionsData = {
  requestBody: Array<number>
}

export type MeSetCinemaSelectionsResponse = Message

export type MeRegisterPushTokenData = {
  requestBody: PushTokenRegister
}

export type MeRegisterPushTokenResponse = Message

export type MeDeletePushTokenData = {
  requestBody: PushTokenDelete
}

export type MeDeletePushTokenResponse = Message

export type MoviesCountMoviesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesCountMoviesResponse = number

export type MoviesReadMoviesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMoviesResponse = Array<MovieSummaryLoggedIn>

export type MoviesReadMovieShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  id: number
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMovieShowtimesResponse = Array<ShowtimeInMovieLoggedIn>

export type MoviesReadMovieData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  id: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMovieResponse = MovieLoggedIn

export type ShowtimesUpdateShowtimeSelectionData = {
  requestBody: ShowtimeSelectionUpdate
  showtimeId: number
}

export type ShowtimesUpdateShowtimeSelectionResponse = ShowtimeLoggedIn

export type ShowtimesPingFriendForShowtimeData = {
  friendId: string
  showtimeId: number
}

export type ShowtimesPingFriendForShowtimeResponse = Message

export type ShowtimesUninviteFriendFromShowtimeData = {
  friendId: string
  showtimeId: number
}

export type ShowtimesUninviteFriendFromShowtimeResponse = Message

export type ShowtimesReceivePingFromLinkData = {
  senderIdentifier: string
  showtimeId: number
}

export type ShowtimesReceivePingFromLinkResponse = Message

export type ShowtimesGetPingedFriendIdsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetPingedFriendIdsForShowtimeResponse = Array<string>

export type ShowtimesGetSentPingsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetSentPingsForShowtimeResponse =
  Array<SentShowtimePingPublic>

export type ShowtimesGetShowtimeVisibilityBatchData = {
  showtimeIds?: Array<number>
}

export type ShowtimesGetShowtimeVisibilityBatchResponse =
  Array<ShowtimeVisibilityPublic>

export type ShowtimesGetShowtimeVisibilityData = {
  showtimeId: number
}

export type ShowtimesGetShowtimeVisibilityResponse = ShowtimeVisibilityPublic

export type ShowtimesUpdateShowtimeVisibilityData = {
  requestBody: ShowtimeVisibilityUpdate
  showtimeId: number
}

export type ShowtimesUpdateShowtimeVisibilityResponse = ShowtimeVisibilityPublic

export type ShowtimesCountMainPageShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type ShowtimesCountMainPageShowtimesResponse = number

export type ShowtimesGetMainPageShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type ShowtimesGetMainPageShowtimesResponse = Array<ShowtimeLoggedIn>

export type ShowtimesGetShowtimeByIdData = {
  showtimeId: number
}

export type ShowtimesGetShowtimeByIdResponse = ShowtimeLoggedIn

export type UsersSearchUsersData = {
  limit?: number
  offset?: number
  query: string
}

export type UsersSearchUsersResponse = Array<UserWithFriendStatus>

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = UserPublic

export type UsersGetUserSelectedShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  userId: string
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type UsersGetUserSelectedShowtimesResponse = Array<ShowtimeLoggedIn>

export type UtilsHealthCheckResponse = boolean

export type UtilsOverrideTmdbCacheEntryData = {
  requestBody: TmdbCacheOverrideRequest
}

export type UtilsOverrideTmdbCacheEntryResponse = TmdbCacheOverrideResponse
