// This file is auto-generated by @hey-api/openapi-ts

export type AdminMoviePublic = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  description?: string | null
}

export type AdminShowtimePublic = {
  id: number
  datetime: string
  end_datetime: string | null
  ticket_link: string | null
  subtitles: Array<string> | null
  movie_id: number
  movie_title: string
  cinema_id: number
  cinema_name: string
  cinema_url: string
}

export type AdminShowtimeUpdate = {
  datetime?: string | null
  end_datetime?: string | null
  ticket_link?: string | null
  subtitles?: Array<string> | null
  movie_id?: number | null
  cinema_id?: number | null
}

export type AnalyticsEventCreate = {
  name: AnalyticsEventName
  properties?: {
    [key: string]: unknown
  } | null
}

/**
 * Closed set of client/server-fired usage events recorded for the beta.
 *
 * Fired via POST /me/events from web/mobile (except LOGIN, which the login
 * route records itself) and aggregated by app/services/analytics_dashboard.py.
 */
export type AnalyticsEventName =
  | "login"
  | "app_open"
  | "filter_applied"
  | "preset_used"
  | "invite_sent"
  | "notification_clicked"
  | "tip_shown"
  | "tip_reacted"

export type AnalyticsOverview = {
  window_days: number
  total_users: number
  users_with_push_token: number
  opens_by_day_user: Array<OpensByDayUser>
  event_counts: {
    [key: string]: number
  }
  invites_sent: number
  invites_opened: number
  notification_opt_in: Array<NotificationOptInBreakdown>
  notifications_sent: number
  notifications_clicked: number
}

/**
 * One row of the "Blocked accounts" list.
 *
 * Carries the display name rather than only the id so the list is readable
 * without a second request per row — the blocked user is deliberately not
 * reachable through search any more, so the client cannot look them up.
 */
export type BlockedUserPublic = {
  id: string
  display_name: string | null
  blocked_at: string
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CinemaPresetCreate = {
  name: string
  cinema_ids?: Array<number>
  is_favorite?: boolean | null
  overwrite?: boolean
}

export type CinemaPresetPublic = {
  id: string
  name: string
  is_default: boolean
  cinema_ids: Array<number>
  cinema_scope?: CinemaScope | null
  is_favorite: boolean
  created_at: string
  updated_at: string
}

/**
 * The only field of a saved preset the user can edit after the fact.
 *
 * Its cinemas are changed by re-picking them in the sheet and saving over the
 * preset, so a rename never carries a selection with it.
 */
export type CinemaPresetRename = {
  name: string
}

export type CinemaPublic = {
  /**
   * Display name of the cinema, shown to users
   */
  name: string
  cineville: boolean
  badge_bg_color: string
  url: string
  seating?: CinemaSeatingPreset
  id: number
  city: CityPublic
}

/**
 * A cinema selection as a rule rather than a frozen list of ids.
 *
 * The three parts are a union: the selection is every cinema (``all_cinemas``),
 * or everything in ``city_ids`` together with everything in ``cinema_ids``.
 * ``all_cinemas`` subsumes the other two, which are left empty when it is set.
 */
export type CinemaScope = {
  all_cinemas?: boolean
  city_ids?: Array<number>
  cinema_ids?: Array<number>
}

/**
 * The seat labelling format used by a cinema.
 *
 * The value encodes the format as "{row_type}-{seat_type}". For assigned-seating
 * presets, the type is either "number" (1-2 digits) or "letter" (a single letter).
 *
 * Values:
 * - unknown:        Row and seat can be a letter or 1-2 digits (flexible default).
 * - free:           No assigned seating — no row/seat input allowed.
 * - number-number:  Row is 1-2 digits, seat is 1-2 digits. E.g. row=3, seat=12.
 * - letter-number:  Row is a letter, seat is 1-2 digits. E.g. row=B, seat=12.
 * - number-letter:  Row is 1-2 digits, seat is a letter. E.g. row=3, seat=C.
 * - letter-letter:  Row is a letter, seat is a letter. E.g. row=B, seat=C.
 */
export type CinemaSeatingPreset =
  | "unknown"
  | "free"
  | "number-number"
  | "letter-number"
  | "number-letter"
  | "letter-letter"

export type CityPublic = {
  /**
   * Name of the city
   */
  name: string
  /**
   * ID of the city
   */
  id: number
}

/**
 * A friend who was invited by the same person who invited you.
 *
 * `inviter` is whichever of your active inviters sent that friend their
 * invite — used to attribute the friend in the "Invited" list ("Invited by
 * <inviter>").
 */
export type CoInvitedFriendPublic = {
  friend: UserPublic
  inviter: UserPublic
}

/**
 * How often a user wants to receive the watchlist new-showtime email digest.
 *
 * DAILY mails you the day a watchlisted film becomes available, however far
 * out its first showtime is — it exists so you can book months ahead for the
 * screenings that sell out. Shown as "Eager".
 *
 * WEEKLY_OR_URGENT mails you once, on Thursday morning, and only about films
 * screening within the next seven days. A film whose showtimes are all
 * further out is not dropped: it stays queued until one of them comes within
 * the week. Shown as "Weekly".
 *
 * The WEEKLY_OR_URGENT name is a leftover: the "or urgent" half — an early
 * send when a pending showtime was within three days — was removed, but the
 * stored/wire value is deliberately left alone so installed app builds keep
 * round-tripping it. Rename it only alongside a client version floor.
 *
 * See app/services/watchlist_digest.py.
 */
export type DigestFrequency = "daily" | "weekly_or_urgent"

export type DigestFrequencyInfo = {
  label: string
  description: string
}

export type DigestFrequencyInfoResponse = {
  daily: DigestFrequencyInfo
  weekly_or_urgent: DigestFrequencyInfo
}

export type FriendStatusSharingUpdate = {
  shares_status: boolean
}

/**
 * Whether a user intends to attend a showtime.
 *
 * Stored on ShowtimeSelection rows and used in visibility calculations.
 */
export type GoingStatus = "GOING" | "NOT_GOING" | "INTERESTED"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Languages selectable in the language filter.
 *
 * Values are ISO-639-1 codes matching ``Movie.original_language`` and the
 * codes found in ``Showtime.subtitles``.
 */
export type Language = "nl" | "en"

export type LetterboxdListCreate = {
  url: string
}

export type LetterboxdListPublic = {
  id: string
  owner: string
  list_slug: string
  title: string | null
  url: string
  is_curated: boolean
  last_updated_on_letterboxd: string | null
  last_synced: string | null
  film_count: number
}

export type Message = {
  message: string
}

export type MovieInShowtime = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  description?: string | null
}

/**
 * A movie page: the film, and every screening matching the filters.
 */
export type MoviePublic = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  description?: string | null
  showtimes: Array<ShowtimeInMoviePublic>
  viewer?: MovieViewerState | null
  /**
   * @deprecated
   */
  readonly friends_watchlisted?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_watched?: Array<UserPublic>
}

/**
 * A movie card: the film, and the screenings it currently has.
 */
export type MovieSummaryPublic = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  directors?: Array<string> | null
  cast?: Array<string> | null
  release_year?: number | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  description?: string | null
  showtimes: Array<ShowtimeInMoviePublic>
  cinemas: Array<CinemaPublic>
  last_showtime_datetime: string | null
  total_showtimes: number
  viewer?: MovieSummaryViewerState | null
  /**
   * @deprecated
   */
  readonly going?: GoingStatus
  /**
   * @deprecated
   */
  readonly friends_going?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_interested?: Array<UserPublic>
}

/**
 * What a movie card means to the person who asked for it.
 *
 * Same reasoning as `ShowtimeViewerState`: everything here is about the
 * requester rather than the film, so it is carried apart from it and is
 * absent — not empty — when there is no requester.
 */
export type MovieSummaryViewerState = {
  going: GoingStatus
  friends_going?: Array<UserPublic>
  friends_interested?: Array<UserPublic>
}

export type MovieUpdate = {
  title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  duration?: number | null
  languages?: Array<string> | null
  original_language?: string | null
  cast?: Array<string> | null
  description?: string | null
  tmdb_last_enriched_at?: string | null
  tmdb_cache_id?: number | null
}

/**
 * What a movie page means to the person who asked for it.
 */
export type MovieViewerState = {
  friends_watchlisted?: Array<UserPublic>
  friends_watched?: Array<UserPublic>
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * A non-friend in the viewer's invite graph for a showtime (identity only,
 * no going/interested status — the client offers a friend-request control
 * instead).
 *
 * Attribution mirrors `CoInvitedFriendPublic`'s "Invited by <inviter>"
 * convention, plus the two direct cases: `invited_by_you` (the viewer
 * invited them) and `invited_you` (they invited the viewer). At most one of
 * `invited_by_you`, `invited_you`, `inviter` is set.
 */
export type NonFriendParticipantPublic = {
  user: UserWithFriendStatus
  invited_by_you?: boolean
  invited_you?: boolean
  inviter?: UserPublic | null
}

/**
 * The delivery mechanism for a notification sent to a user.
 */
export type NotificationChannel = "push" | "email"

/**
 * One merged, time-sorted entry in the notification centre.
 *
 * The three sources (the ``notification`` table, received ``ShowtimePing``
 * rows, received ``FriendRequest`` rows) are normalised into this shape so the
 * client renders a single feed. ``source`` + ``id`` identify the underlying
 * row for actions.
 */
export type NotificationFeedItem = {
  source: "notification" | "ping" | "friend_request"
  id: string
  type:
    | "friend_showtime_match"
    | "showtime_invite"
    | "invite_response"
    | "friend_request_received"
    | "friend_request_accepted"
    | "seats_released"
    | "seats_running_out"
  created_at: string
  seen_at: string | null
  actor: UserPublic | null
  showtime: ShowtimePublic | null
}

export type source = "notification" | "ping" | "friend_request"

export type type =
  | "friend_showtime_match"
  | "showtime_invite"
  | "invite_response"
  | "friend_request_received"
  | "friend_request_accepted"
  | "seats_released"
  | "seats_running_out"

export type NotificationOptInBreakdown = {
  setting: string
  enabled_count: number
  disabled_count: number
}

export type OpensByDayUser = {
  day: string
  user_id: string
  user_email: string
  platform: string | null
  count: number
}

export type PushTokenDelete = {
  token: string
}

export type PushTokenRegister = {
  token: string
  platform?: "ios" | "android" | "web" | null
}

export type RefreshTokenRequest = {
  refresh_token: string
}

export type SavedPresetCreate = {
  name: string
  untouched_fields?: Array<string>
  filters: SavedPresetFilters
  cinema_ids?: Array<number> | null
  is_favorite?: boolean | null
}

export type SavedPresetFilters = {
  selected_showtime_filter?: "all" | "interested" | "going" | null
  showtime_audience?: "including-friends" | "only-you"
  watchlist_only?: boolean
  watchlist_exclude?: boolean
  hide_watched?: boolean
  watched_only?: boolean
  selected_list_ids?: Array<string> | null
  exclude_list_ids?: Array<string> | null
  days?: Array<string> | null
  time_ranges?: Array<string> | null
  runtime_ranges?: Array<string> | null
  group_by_movie?: boolean | null
  selected_languages?: Array<Language> | null
}

export type showtime_audience = "including-friends" | "only-you"

export type SavedPresetPublic = {
  id: string
  name: string
  is_favorite: boolean
  untouched_fields: Array<string>
  filters: SavedPresetFilters
  cinema_ids: Array<number> | null
  cinema_scope?: CinemaScope | null
  created_at: string
  updated_at: string
}

export type ScrapeMonitorResponse = {
  summary: ScrapeMonitorSummary
  runs: Array<ScrapeRunView>
}

export type ScrapeMonitorSummary = {
  window_hours: number
  generated_at: string
  total_runs: number
  failed_runs: number
  degraded_runs: number
  anomaly_runs: number
  streams_with_anomalies: Array<string>
}

export type ScrapeRecapAttachment = {
  filename: string
  mime_type: string
  size_bytes: number
}

export type ScrapeRecapDetail = {
  id: number
  started_at: string
  finished_at: string
  subject: string
  created_at: string
  html: string
  attachments: Array<ScrapeRecapAttachment>
}

export type ScrapeRecapView = {
  id: number
  started_at: string
  finished_at: string
  subject: string
  created_at: string
}

export type ScrapeRunView = {
  id: number
  source_stream: string
  source_label: string
  status: string
  started_at: string
  finished_at: string | null
  duration_seconds: number | null
  observed_showtime_count: number | null
  previous_observed_count: number | null
  delta: number | null
  error: string | null
  is_failed: boolean
  is_degraded: boolean
  is_zero_observed: boolean
  is_big_drop: boolean
  readonly is_anomaly: boolean
}

/**
 * Which attribute the movie search ``query`` is matched against.
 *
 * TITLE also matches ``original_title``; the others match arrays/related
 * tables rather than a single Movie column — see ``apply_search_filter``.
 */
export type SearchField = "title" | "director" | "actor" | "cinema" | "friend"

/**
 * How full a screening is, as a handful of buckets rather than a number.
 *
 * Derived from `Showtime.seats_left` against `seats_capacity` — see
 * `app.services.seat_availability.seat_availability_level`, which is the only
 * place the cutoffs live. A showtime we have no usable reading for has no
 * level at all (`None`), which is deliberately not a value here: "we don't
 * know" must never be renderable as "it's fine".
 *
 * Declaration order is emptiest-first and is load-bearing: `SEAT_LEVEL_ORDER`
 * below reads it to compare two levels, which is what lets a showtime's level
 * ratchet upwards and never fall back.
 */
export type SeatAvailabilityLevel =
  | "some_taken"
  | "busy"
  | "very_busy"
  | "last_few"
  | "sold_out"

/**
 * A room's seat map for one showtime, merged with polled + personal state.
 */
export type SeatFloorPlanPublic = {
  showtime_id: number
  room: string
  seats: Array<SeatFloorPlanSeatPublic>
  seats_checked_at?: string | null
}

/**
 * One seat's position and status on a room's floor plan.
 *
 * Geometry (`position_left/top`, `width`, `height`) is the room's own,
 * stored once and never refreshed. `taken` comes from the availability
 * poller's last reading of this showtime, so it is exactly as fresh as the
 * seat count shown next to it and no ticket shop is read to answer this;
 * `is_viewer_seat`/`friend_count` are computed per request from this
 * showtime's selections.
 */
export type SeatFloorPlanSeatPublic = {
  row_name: string
  seat_name: string
  position_left: number
  position_top: number
  width: number
  height: number
  selectable: boolean
  taken: boolean | null
  is_viewer_seat: boolean
  friend_count?: number
}

export type SentShowtimePingPublic = {
  id: number
  receiver_id: string
  receiver_name: string
  created_at: string
  seen_at: string | null
  dismissed_at: string | null
}

/**
 * A screening listed under a movie, so it carries no movie of its own.
 */
export type ShowtimeInMoviePublic = {
  datetime: string
  end_datetime?: string | null
  ticket_link?: string | null
  room?: string | null
  subtitles?: Array<string> | null
  scrape_source?: string | null
  tmdb_cache_id?: number | null
  id: number
  cinema: CinemaPublic
  viewer?: ShowtimeInMovieViewerState | null
  /**
   * @deprecated
   */
  readonly going?: GoingStatus
  /**
   * @deprecated
   */
  readonly seat_row?: string | null
  /**
   * @deprecated
   */
  readonly seat_number?: string | null
  /**
   * @deprecated
   */
  readonly friends_going?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_interested?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly invited_by?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly invite_ping_ids?: Array<number>
  /**
   * @deprecated
   */
  readonly co_invited_friends?: Array<CoInvitedFriendPublic>
  /**
   * @deprecated
   */
  readonly pending_invited_friends?: Array<UserPublic>
}

/**
 * What a showtime means to the person who asked for it.
 *
 * Kept apart from the showtime itself because it is the one part of the
 * response that is *not* the same for everyone: the screening is public, this
 * is the requester's own relationship to it. Carried as `viewer` on the
 * schemas below, where `None` means nobody was asking — see `app.core.viewer`.
 * Nesting it rather than flattening it is what makes those two cases
 * distinguishable at all: a flat `friends_going: []` cannot say whether the
 * viewer has no friends going or whether there is no viewer.
 */
export type ShowtimeInMovieViewerState = {
  going: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  friends_going?: Array<UserPublic>
  friends_interested?: Array<UserPublic>
  invited_by?: Array<UserPublic>
  invite_ping_ids?: Array<number>
  co_invited_friends?: Array<CoInvitedFriendPublic>
  pending_invited_friends?: Array<UserPublic>
}

export type ShowtimePingLinkToken = {
  token: string
}

export type ShowtimePingPublic = {
  id: number
  showtime_id: number
  movie_id: number
  movie_title: string
  movie_poster_link: string | null
  cinema_name: string
  datetime: string
  ticket_link: string | null
  showtime: ShowtimePublic
  sender: UserPublic
  created_at: string
  seen_at: string | null
}

/**
 * Sort order options for the pings list endpoint.
 */
export type ShowtimePingSort = "ping_created_at" | "showtime_datetime"

/**
 * A screening: which film, which cinema, when, and where to buy a ticket.
 *
 * Public in the literal sense — identical for everyone and served without a
 * token. Anything that varies by who is asking lives under `viewer`.
 */
export type ShowtimePublic = {
  datetime: string
  end_datetime?: string | null
  ticket_link?: string | null
  room?: string | null
  subtitles?: Array<string> | null
  scrape_source?: string | null
  tmdb_cache_id?: number | null
  id: number
  movie: MovieInShowtime
  cinema: CinemaPublic
  viewer?: ShowtimeViewerState | null
  /**
   * @deprecated
   */
  readonly going?: GoingStatus
  /**
   * @deprecated
   */
  readonly seat_row?: string | null
  /**
   * @deprecated
   */
  readonly seat_number?: string | null
  /**
   * @deprecated
   */
  readonly friends_going?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_interested?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly invited_by?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly invite_ping_ids?: Array<number>
  /**
   * @deprecated
   */
  readonly co_invited_friends?: Array<CoInvitedFriendPublic>
  /**
   * @deprecated
   */
  readonly pending_invited_friends?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_watchlisted?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly friends_watched?: Array<UserPublic>
  /**
   * @deprecated
   */
  readonly non_friend_participants?: Array<NonFriendParticipantPublic>
}

export type ShowtimeReportAdminView = {
  id: number
  showtime_id: number
  movie_id: number
  movie_title: string
  cinema_id: number
  cinema_name: string
  cinema_url: string
  showtime_datetime: string
  ticket_link: string | null
  reporter_id: string
  reporter_email: string
  reporter_report_banned: boolean
  reason: ShowtimeReportReason
  message: string | null
  status: ShowtimeReportStatus
  created_at: string
  resolved_at: string | null
  report_count: number
}

export type ShowtimeReportCreate = {
  reason: ShowtimeReportReason
  message?: string | null
}

/**
 * Why a user is flagging a showtime as wrong.
 */
export type ShowtimeReportReason =
  | "incorrect_movie"
  | "incorrect_time"
  | "does_not_exist"
  | "duplicate"
  | "wrong_subtitles"
  | "other"

/**
 * Moderation state of a user-submitted showtime report.
 */
export type ShowtimeReportStatus = "open" | "resolved" | "dismissed"

export type ShowtimeReportUpdate = {
  status: ShowtimeReportStatus
}

/**
 * How full a screening is, and how much we can say about it.
 *
 * The same for everyone — this is a fact about the screening, not about who
 * asked — which is what lets it be cached per showtime and prefetched for a
 * whole list at once. A showtime with no usable reading and no read pending
 * is simply absent from the response rather than present with a null level,
 * so the client never has to tell "empty" from "unknown". A showtime whose
 * reading has not landed yet, but is expected soon, is the one exception: it
 * is present with `checking` set — with a level if it has ever had one, and
 * without if this is its first — so the client can say a number is coming
 * instead of showing nothing or a stale one with no explanation.
 */
export type ShowtimeSeatAvailabilityPublic = {
  showtime_id: number
  level?: SeatAvailabilityLevel | null
  seats_left?: number | null
  seats_capacity?: number | null
  checked_at?: string | null
  watchable?: boolean
  checking?: boolean
}

export type ShowtimeSelectionUpdate = {
  going_status: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  visibility_mode?: VisibilityMode | null
}

/**
 * The full viewer state, for the showtime sheet.
 *
 * The extra fields cost queries that a list of rows does not pay for, which is
 * why the two shapes differ rather than one carrying empty defaults — an empty
 * list should mean "none", never "we didn't look".
 */
export type ShowtimeViewerState = {
  going: GoingStatus
  seat_row?: string | null
  seat_number?: string | null
  friends_going?: Array<UserPublic>
  friends_interested?: Array<UserPublic>
  invited_by?: Array<UserPublic>
  invite_ping_ids?: Array<number>
  co_invited_friends?: Array<CoInvitedFriendPublic>
  pending_invited_friends?: Array<UserPublic>
  friends_watchlisted?: Array<UserPublic>
  friends_watched?: Array<UserPublic>
  non_friend_participants?: Array<NonFriendParticipantPublic>
}

export type ShowtimeVisibilityPublic = {
  showtime_id: number
  movie_id: number
  mode: VisibilityMode
}

export type ShowtimeVisibilityUpdate = {
  mode: VisibilityMode
}

/**
 * Made-up numbers for the superuser simulation hook (never production).
 */
export type SimulateSeatAvailability = {
  seats_left?: number | null
  seats_capacity?: number | null
  reset?: boolean
}

export type SocialLoginRequest = {
  provider: SocialProvider
  token: string
  authorization_code?: string | null
}

export type SocialLoginResponse = {
  access_token: string
  refresh_token: string
  /**
   * Type of the token, usually 'bearer'
   */
  token_type?: string
  needs_username?: boolean
  password_removed?: boolean
}

/**
 * Third-party identity provider for social sign-in.
 */
export type SocialProvider = "apple" | "google"

export type SoldOutWatchPublic = {
  showtime_id: number
  created_at: string
}

/**
 * Coarse time-of-day bucket used for showtime filtering.
 *
 * Showtimes are bucketed into one of these values based on their start time,
 * allowing users to filter by "evening showings" etc. without specifying exact
 * hour ranges.
 */
export type TimeOfDay = "MORNING" | "AFTERNOON" | "EVENING" | "NIGHT"

export type TmdbCacheCorrectionRequest = {
  cache_id: number
  tmdb_id?: number | null
  confidence?: number | null
}

export type TmdbCacheOverrideRequest = {
  title_query: string
  director_names?: Array<string>
  actor_name?: string | null
  year?: number | null
  duration_minutes?: number | null
  spoken_languages?: Array<string> | null
  tmdb_id?: number | null
  confidence?: number | null
}

export type TmdbCacheOverrideResponse = {
  lookup_hash: string
  lookup_payload: string
  tmdb_id: number | null
  confidence: number | null
}

export type TmdbCacheSearchResult = {
  id: number
  lookup_payload: string
  tmdb_id: number | null
  confidence: number | null
}

export type Token = {
  access_token: string
  refresh_token: string
  /**
   * Type of the token, usually 'bearer'
   */
  token_type?: string
}

export type UninvitedSelectedFriendsPublic = {
  friends: Array<UserPublic>
}

export type UpdatePassword = {
  current_password?: string | null
  new_password: string
}

export type UserMe = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
  email: string
  email_verified: boolean
  show_watchlist_digest_tip: boolean
  is_superuser: boolean
  incognito_mode: boolean
  notify_on_friend_showtime_match: boolean
  notify_on_friend_requests: boolean
  notify_on_showtime_ping: boolean
  notify_on_invite_response: boolean
  notify_on_interest_reminder: boolean
  notify_on_seat_alert: boolean
  notify_channel_friend_showtime_match: NotificationChannel
  notify_channel_friend_requests: NotificationChannel
  notify_channel_showtime_ping: NotificationChannel
  notify_channel_invite_response: NotificationChannel
  notify_channel_interest_reminder: NotificationChannel
  notify_channel_seat_alert: NotificationChannel
  letterboxd_username: string | null
  watchlist_count: number
  watched_count: number
  watchlist_last_synced?: string | null
  watched_last_synced?: string | null
  watchlist_last_sync_attempt?: string | null
  watched_last_sync_attempt?: string | null
  watchlist_sync_failed?: boolean
  watched_sync_failed?: boolean
  watchlist_sync_cooldown_ends_at?: string | null
  watched_sync_cooldown_ends_at?: string | null
  notify_watchlist_digest_enabled: boolean
  notify_watchlist_digest_frequency: DigestFrequency
  notify_watchlist_digest_list_id: string | null
  notify_watchlist_digest_cinema_preset_id: string | null
  can_report: boolean
  can_watch_sold_out: boolean
  has_password: boolean
}

export type UserPublic = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
}

export type UserRegister = {
  email: string
  password: string
  display_name?: string | null
}

export type UserReportAdminView = {
  id: number
  reported_id: string
  reported_display_name: string | null
  reported_email: string
  reporter_id: string
  reporter_email: string
  reason: UserReportReason
  message: string | null
  status: UserReportStatus
  created_at: string
  resolved_at: string | null
  report_count: number
}

export type UserReportBanUpdate = {
  banned: boolean
  duration_days?: number | null
}

export type UserReportCreate = {
  reason: UserReportReason
  message?: string | null
  block_user?: boolean
}

/**
 * Why a user is reporting another user.
 *
 * Scoped to what is actually possible in MiKiNO: there is no messaging or
 * free-text between users, so reasons like harassment or bullying (which
 * would need a channel to say something in) don't apply. What remains is
 * what a username, a friend request, or an invite can actually do wrong.
 */
export type UserReportReason =
  | "objectionable_username"
  | "impersonation"
  | "repeated_unwanted_contact"
  | "spam"
  | "other"

/**
 * Moderation state of a user-submitted report about another user.
 *
 * Mirrors `ShowtimeReportStatus` rather than sharing it: the two queues are
 * triaged separately and nothing should make it possible to move a report
 * about a person into a state that only means something for a screening.
 */
export type UserReportStatus = "open" | "resolved" | "dismissed"

export type UserReportUpdate = {
  status: UserReportStatus
}

export type UserUpdate = {
  display_name?: string | null
  email?: string | null
  letterboxd_username?: string | null
  incognito_mode?: boolean | null
  notify_on_friend_showtime_match?: boolean | null
  notify_on_friend_requests?: boolean | null
  notify_on_showtime_ping?: boolean | null
  notify_on_invite_response?: boolean | null
  notify_on_interest_reminder?: boolean | null
  notify_on_seat_alert?: boolean | null
  notify_channel_friend_showtime_match?: NotificationChannel | null
  notify_channel_friend_requests?: NotificationChannel | null
  notify_channel_showtime_ping?: NotificationChannel | null
  notify_channel_invite_response?: NotificationChannel | null
  notify_channel_interest_reminder?: NotificationChannel | null
  notify_channel_seat_alert?: NotificationChannel | null
  notify_watchlist_digest_enabled?: boolean | null
  notify_watchlist_digest_frequency?: DigestFrequency | null
  notify_watchlist_digest_list_id?: string | null
  notify_watchlist_digest_cinema_preset_id?: string | null
  password?: string | null
  current_password?: string | null
}

export type UserWithFriendStatus = {
  id: string
  is_active: boolean
  display_name: string | null
  seat_row?: string | null
  seat_number?: string | null
  is_friend: boolean
  sent_request: boolean
  received_request: boolean
  shares_status?: boolean
  is_blocked?: boolean
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

/**
 * Who may see a user's attendance status for a showtime.
 *
 * Stored per showtime on ShowtimeVisibilitySetting.
 *
 * - ALL_FRIENDS: every friend you haven't opted out of sharing with.
 * - INVITED_ONLY: nobody by default.
 *
 * Regardless of the mode, your status is always visible to friends you
 * invited, friends who invited you, and friends co-invited by the same person
 * who invited you.
 */
export type VisibilityMode = "ALL_FRIENDS" | "INVITED_ONLY"

export type AdminSimulateSeatAvailabilityData = {
  requestBody: SimulateSeatAvailability
  showtimeId: number
}

export type AdminSimulateSeatAvailabilityResponse =
  ShowtimeSeatAvailabilityPublic | null

export type AdminGetAnalyticsOverviewData = {
  windowDays?: number
}

export type AdminGetAnalyticsOverviewResponse = AnalyticsOverview

export type AdminSearchMoviesData = {
  limit?: number
  q: string
}

export type AdminSearchMoviesResponse = Array<AdminMoviePublic>

export type AdminUpdateMovieData = {
  movieId: number
  requestBody: MovieUpdate
}

export type AdminUpdateMovieResponse = AdminMoviePublic

export type AdminSearchShowtimesData = {
  cinemaId?: number | null
  fromDatetime?: string | null
  limit?: number
  movieId?: number | null
  offset?: number
  toDatetime?: string | null
}

export type AdminSearchShowtimesResponse = Array<AdminShowtimePublic>

export type AdminGetShowtimeData = {
  showtimeId: number
}

export type AdminGetShowtimeResponse = AdminShowtimePublic

export type AdminUpdateShowtimeData = {
  requestBody: AdminShowtimeUpdate
  showtimeId: number
}

export type AdminUpdateShowtimeResponse = AdminShowtimePublic

export type AdminDeleteShowtimeData = {
  showtimeId: number
}

export type AdminDeleteShowtimeResponse = Message

export type AdminListShowtimeReportsData = {
  status?: ShowtimeReportStatus | null
}

export type AdminListShowtimeReportsResponse = Array<ShowtimeReportAdminView>

export type AdminUpdateShowtimeReportData = {
  reportId: number
  requestBody: ShowtimeReportUpdate
}

export type AdminUpdateShowtimeReportResponse = Message

export type AdminListUserReportsData = {
  status?: UserReportStatus | null
}

export type AdminListUserReportsResponse = Array<UserReportAdminView>

export type AdminUpdateUserReportData = {
  reportId: number
  requestBody: UserReportUpdate
}

export type AdminUpdateUserReportResponse = Message

export type AdminUpdateUserReportBanData = {
  requestBody: UserReportBanUpdate
  userId: string
}

export type AdminUpdateUserReportBanResponse = Message

export type AdminGetScrapeRunsData = {
  hours?: number
}

export type AdminGetScrapeRunsResponse = ScrapeMonitorResponse

export type AdminListScrapeRecapsData = {
  limit?: number
}

export type AdminListScrapeRecapsResponse = Array<ScrapeRecapView>

export type AdminGetScrapeRecapData = {
  recapId: number
}

export type AdminGetScrapeRecapResponse = ScrapeRecapDetail

export type AdminGetScrapeRecapAttachmentData = {
  filename: string
  recapId: number
}

export type AdminGetScrapeRecapAttachmentResponse = unknown

export type CinemasGetAllCinemasResponse = Array<CinemaPublic>

export type FriendsSendFriendRequestData = {
  receiverId: string
}

export type FriendsSendFriendRequestResponse = Message

export type FriendsAcceptFriendRequestData = {
  senderId: string
}

export type FriendsAcceptFriendRequestResponse = Message

export type FriendsDeclineFriendRequestData = {
  senderId: string
}

export type FriendsDeclineFriendRequestResponse = Message

export type FriendsCancelFriendRequestData = {
  receiverId: string
}

export type FriendsCancelFriendRequestResponse = Message

export type FriendsSetFriendStatusSharingData = {
  friendId: string
  requestBody: FriendStatusSharingUpdate
}

export type FriendsSetFriendStatusSharingResponse = Message

export type FriendsRemoveFriendData = {
  friendId: string
}

export type FriendsRemoveFriendResponse = Message

export type LetterboxdListsGetCuratedLetterboxdListsResponse =
  Array<LetterboxdListPublic>

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginLoginSocialTokenData = {
  requestBody: SocialLoginRequest
}

export type LoginLoginSocialTokenResponse = SocialLoginResponse

export type LoginRefreshAccessTokenData = {
  requestBody: RefreshTokenRequest
}

export type LoginRefreshAccessTokenResponse = Token

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type MeGetCurrentUserResponse = UserMe

export type MeDeleteUserMeResponse = Message

export type MeUpdateUserMeData = {
  requestBody: UserUpdate
}

export type MeUpdateUserMeResponse = UserMe

export type MeGetSavedPresetsResponse = Array<SavedPresetPublic>

export type MeCreateSavedPresetData = {
  requestBody: SavedPresetCreate
}

export type MeCreateSavedPresetResponse = SavedPresetPublic

export type MeGetFavoriteSavedPresetResponse = SavedPresetPublic | null

export type MeClearFavoriteSavedPresetResponse = Message

export type MeSetFavoriteSavedPresetData = {
  presetId: string
}

export type MeSetFavoriteSavedPresetResponse = SavedPresetPublic

export type MeDeleteSavedPresetData = {
  presetId: string
}

export type MeDeleteSavedPresetResponse = Message

export type MeGetCinemaPresetsResponse = Array<CinemaPresetPublic>

export type MeCreateCinemaPresetData = {
  requestBody: CinemaPresetCreate
}

export type MeCreateCinemaPresetResponse = CinemaPresetPublic

export type MeGetFavoriteCinemaPresetResponse = CinemaPresetPublic | null

export type MeClearFavoriteCinemaPresetResponse = Message

export type MeRenameCinemaPresetData = {
  presetId: string
  requestBody: CinemaPresetRename
}

export type MeRenameCinemaPresetResponse = CinemaPresetPublic

export type MeDeleteCinemaPresetData = {
  presetId: string
}

export type MeDeleteCinemaPresetResponse = Message

export type MeSetFavoriteCinemaPresetData = {
  presetId: string
}

export type MeSetFavoriteCinemaPresetResponse = CinemaPresetPublic

export type MeResendEmailVerificationResponse = Message

export type MeUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type MeUpdatePasswordMeResponse = Message

export type MeCountMyShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MeCountMyShowtimesResponse = number

export type MeGetMyShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MeGetMyShowtimesResponse = Array<ShowtimePublic>

export type MeGetMyAgendaData = {
  includeInterested?: boolean
  includeInvited?: boolean
  limit?: number
  offset?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
}

export type MeGetMyAgendaResponse = Array<ShowtimePublic>

export type MeGetMyShowtimePingsData = {
  limit?: number
  offset?: number
  sortBy?: ShowtimePingSort
}

export type MeGetMyShowtimePingsResponse = Array<ShowtimePingPublic>

export type MeGetMyUnseenShowtimePingCountResponse = number

export type MeMarkMyShowtimePingsSeenResponse = Message

export type MeDeleteMyShowtimePingData = {
  pingId: number
}

export type MeDeleteMyShowtimePingResponse = Message

export type MeDismissMyShowtimePingData = {
  pingId: number
}

export type MeDismissMyShowtimePingResponse = Message

export type MeGetMyNotificationsData = {
  limit?: number
  offset?: number
}

export type MeGetMyNotificationsResponse = Array<NotificationFeedItem>

export type MeGetMyUnseenNotificationCountResponse = number

export type MeMarkMyNotificationsSeenResponse = Message

export type MeDismissMyNotificationData = {
  notificationId: number
}

export type MeDismissMyNotificationResponse = Message

export type MeSyncWatchlistResponse = Message

export type MeSyncWatchedResponse = Message

export type MeGetLetterboxdListsResponse = Array<LetterboxdListPublic>

export type MeAddLetterboxdListData = {
  requestBody: LetterboxdListCreate
}

export type MeAddLetterboxdListResponse = LetterboxdListPublic

export type MeSyncLetterboxdListData = {
  listId: string
}

export type MeSyncLetterboxdListResponse = LetterboxdListPublic

export type MeRemoveLetterboxdListData = {
  listId: string
}

export type MeRemoveLetterboxdListResponse = Message

export type MeGetFriendsResponse = Array<UserWithFriendStatus>

export type MeGetBlockedUsersResponse = Array<BlockedUserPublic>

export type MeGetSentFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetReceivedFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetCinemaSelectionsResponse = Array<number>

export type MeSetCinemaSelectionsData = {
  requestBody: Array<number>
}

export type MeSetCinemaSelectionsResponse = Message

export type MeRegisterPushTokenData = {
  requestBody: PushTokenRegister
}

export type MeRegisterPushTokenResponse = Message

export type MeDeletePushTokenData = {
  requestBody: PushTokenDelete
}

export type MeDeletePushTokenResponse = Message

export type MeRecordEventData = {
  requestBody: AnalyticsEventCreate
}

export type MeRecordEventResponse = void

export type MoviesCountMoviesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesCountMoviesResponse = number

export type MoviesReadMoviesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMoviesResponse = Array<MovieSummaryPublic>

export type MoviesReadMovieShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  id: number
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMovieShowtimesResponse = Array<ShowtimeInMoviePublic>

export type MoviesReadMovieData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  id: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  showtimeLimit?: number | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type MoviesReadMovieResponse = MoviePublic

export type ScrapeMonitorGetScrapeRunsData = {
  hours?: number
}

export type ScrapeMonitorGetScrapeRunsResponse = ScrapeMonitorResponse

export type ScrapeMonitorListScrapeRecapsData = {
  limit?: number
}

export type ScrapeMonitorListScrapeRecapsResponse = Array<ScrapeRecapView>

export type ScrapeMonitorGetScrapeRecapData = {
  recapId: number
}

export type ScrapeMonitorGetScrapeRecapResponse = ScrapeRecapDetail

export type ScrapeMonitorGetScrapeRecapAttachmentData = {
  filename: string
  recapId: number
}

export type ScrapeMonitorGetScrapeRecapAttachmentResponse = unknown

export type ShowtimesUpdateShowtimeSelectionData = {
  requestBody: ShowtimeSelectionUpdate
  showtimeId: number
}

export type ShowtimesUpdateShowtimeSelectionResponse = ShowtimePublic

export type ShowtimesGetShowtimeSeatmapData = {
  showtimeId: number
}

export type ShowtimesGetShowtimeSeatmapResponse = SeatFloorPlanPublic | null

export type ShowtimesPingFriendForShowtimeData = {
  friendId: string
  showtimeId: number
}

export type ShowtimesPingFriendForShowtimeResponse = Message

export type ShowtimesUninviteFriendFromShowtimeData = {
  friendId: string
  showtimeId: number
}

export type ShowtimesUninviteFriendFromShowtimeResponse = Message

export type ShowtimesCreateShowtimePingLinkTokenData = {
  showtimeId: number
}

export type ShowtimesCreateShowtimePingLinkTokenResponse = ShowtimePingLinkToken

export type ShowtimesReceivePingFromLinkData = {
  showtimeId: number
  token: string
}

export type ShowtimesReceivePingFromLinkResponse = Message

export type ShowtimesReportShowtimeData = {
  requestBody: ShowtimeReportCreate
  showtimeId: number
}

export type ShowtimesReportShowtimeResponse = Message

export type ShowtimesGetPingedFriendIdsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetPingedFriendIdsForShowtimeResponse = Array<string>

export type ShowtimesGetSentPingsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetSentPingsForShowtimeResponse =
  Array<SentShowtimePingPublic>

export type ShowtimesGetSeatAvailabilityBatchData = {
  showtimeIds?: Array<number>
}

export type ShowtimesGetSeatAvailabilityBatchResponse =
  Array<ShowtimeSeatAvailabilityPublic>

export type ShowtimesGetSeatAvailabilityData = {
  showtimeId: number
}

export type ShowtimesGetSeatAvailabilityResponse =
  ShowtimeSeatAvailabilityPublic | null

export type ShowtimesGetSoldOutWatchResponse = SoldOutWatchPublic | null

export type ShowtimesStopSoldOutWatchResponse = Message

export type ShowtimesStartSoldOutWatchData = {
  showtimeId: number
}

export type ShowtimesStartSoldOutWatchResponse = SoldOutWatchPublic

export type ShowtimesGetShowtimeVisibilityBatchData = {
  showtimeIds?: Array<number>
}

export type ShowtimesGetShowtimeVisibilityBatchResponse =
  Array<ShowtimeVisibilityPublic>

export type ShowtimesGetShowtimeVisibilityData = {
  showtimeId: number
}

export type ShowtimesGetShowtimeVisibilityResponse = ShowtimeVisibilityPublic

export type ShowtimesUpdateShowtimeVisibilityData = {
  requestBody: ShowtimeVisibilityUpdate
  showtimeId: number
}

export type ShowtimesUpdateShowtimeVisibilityResponse = ShowtimeVisibilityPublic

export type ShowtimesGetUninvitedSelectedFriendsForShowtimeData = {
  showtimeId: number
}

export type ShowtimesGetUninvitedSelectedFriendsForShowtimeResponse =
  UninvitedSelectedFriendsPublic

export type ShowtimesCountMainPageShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type ShowtimesCountMainPageShowtimesResponse = number

export type ShowtimesGetMainPageShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type ShowtimesGetMainPageShowtimesResponse = Array<ShowtimePublic>

export type ShowtimesGetShowtimeByIdData = {
  showtimeId: number
}

export type ShowtimesGetShowtimeByIdResponse = ShowtimePublic

export type UsersUnsubscribeWatchlistDigestData = {
  token: string
}

export type UsersUnsubscribeWatchlistDigestResponse = string

export type UsersVerifyEmailData = {
  token: string
}

export type UsersVerifyEmailResponse = string

export type UsersSearchUsersData = {
  limit?: number
  offset?: number
  query: string
}

export type UsersSearchUsersResponse = Array<UserWithFriendStatus>

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersGetUserFriendStatusData = {
  userId: string
}

export type UsersGetUserFriendStatusResponse = UserWithFriendStatus

export type UsersBlockUserData = {
  userId: string
}

export type UsersBlockUserResponse = Message

export type UsersUnblockUserData = {
  userId: string
}

export type UsersUnblockUserResponse = Message

export type UsersReportUserData = {
  requestBody: UserReportCreate
  userId: string
}

export type UsersReportUserResponse = Message

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = UserPublic

export type UsersGetUserSelectedShowtimesData = {
  days?: Array<string> | null
  /**
   * Hide movies on any of these Letterboxd lists
   */
  excludeListIds?: Array<string> | null
  hideWatched?: boolean
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Maximum movie runtime in minutes
   */
  runtimeMax?: number | null
  /**
   * Minimum movie runtime in minutes
   */
  runtimeMin?: number | null
  /**
   * Which attribute `query` is matched against
   */
  searchField?: SearchField
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Keep movies whose main spoken language is one of these, and only showtimes with matching subtitles
   */
  selectedLanguages?: Array<Language> | null
  /**
   * Only show movies on any of these Letterboxd lists
   */
  selectedListIds?: Array<string> | null
  /**
   * Filter by selection statuses (GOING/INTERESTED)
   */
  selectedStatuses?: Array<GoingStatus> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string | null
  timeRanges?: Array<string> | null
  /**
   * Preset time windows (MORNING/AFTERNOON/EVENING/NIGHT)
   */
  timesOfDay?: Array<TimeOfDay> | null
  userId: string
  watchedOnly?: boolean
  watchlistExclude?: boolean
  watchlistOnly?: boolean
}

export type UsersGetUserSelectedShowtimesResponse = Array<ShowtimePublic>

export type UtilsHealthCheckResponse = boolean

export type UtilsGetWatchlistDigestFrequencyInfoResponse =
  DigestFrequencyInfoResponse

export type UtilsSearchTmdbCacheEntriesData = {
  title: string
}

export type UtilsSearchTmdbCacheEntriesResponse = Array<TmdbCacheSearchResult>

export type UtilsCorrectTmdbCacheEntryData = {
  requestBody: TmdbCacheCorrectionRequest
}

export type UtilsCorrectTmdbCacheEntryResponse = TmdbCacheOverrideResponse

export type UtilsOverrideTmdbCacheEntryData = {
  requestBody: TmdbCacheOverrideRequest
}

export type UtilsOverrideTmdbCacheEntryResponse = TmdbCacheOverrideResponse
