FROM node:20

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /app/
COPY tsconfig.json /app/tsconfig.json
COPY frontend/package.json /app/frontend/package.json
COPY shared/package.json /app/shared/package.json

RUN corepack enable && pnpm install --filter frontend... --no-frozen-lockfile --prod=false

WORKDIR /app/frontend
RUN pnpm exec playwright install --with-deps

COPY frontend /app/frontend
COPY shared /app/shared

ARG VITE_API_URL=${VITE_API_URL}
