// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CinemaPublic = {
  /**
   * Name of the cinema
   */
  name: string
  cineville: boolean
  badge_bg_color: string
  url: string
  id: number
  city: CityPublic
}

export type CityPublic = {
  /**
   * Name of the city
   */
  name: string
  /**
   * ID of the city
   */
  id: number
}

export type GoingStatus = "GOING" | "NOT_GOING" | "INTERESTED"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type MovieLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  top250?: number | null
  directors?: Array<string> | null
  release_year?: number | null
  rating?: number | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
}

export type MovieSummaryLoggedIn = {
  id: number
  title: string
  original_title?: string | null
  poster_link?: string | null
  letterboxd_slug?: string | null
  top250?: number | null
  directors?: Array<string> | null
  release_year?: number | null
  rating?: number | null
  showtimes: Array<ShowtimeInMovieLoggedIn>
  cinemas: Array<CinemaPublic>
  last_showtime_datetime: string | null
  total_showtimes: number
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type NewPassword = {
  token: string
  new_password: string
}

export type ShowtimeInMovieLoggedIn = {
  datetime: string
  ticket_link?: string | null
  id: number
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type ShowtimeLoggedIn = {
  datetime: string
  ticket_link?: string | null
  id: number
  movie: MovieSummaryLoggedIn
  cinema: CinemaPublic
  friends_going: Array<UserPublic>
  friends_interested: Array<UserPublic>
  going: GoingStatus
}

export type ShowtimeSelectionUpdate = {
  going_status: GoingStatus
}

export type Token = {
  access_token: string
  /**
   * Type of the token, usually 'bearer'
   */
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  display_name?: string | null
  letterboxd_username?: string | null
  id: string
  last_watchlist_sync: string | null
}

export type UserRegister = {
  email: string
  password: string
  display_name?: string | null
}

export type UserUpdate = {
  display_name?: string | null
  email?: string | null
  letterboxd_username?: string | null
  password?: string | null
}

export type UserWithFriendStatus = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  display_name?: string | null
  letterboxd_username?: string | null
  id: string
  last_watchlist_sync: string | null
  is_friend: boolean
  sent_request: boolean
  received_request: boolean
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CinemasGetAllCinemasResponse = Array<CinemaPublic>

export type FriendsSendFriendRequestData = {
  receiverId: string
}

export type FriendsSendFriendRequestResponse = Message

export type FriendsAcceptFriendRequestData = {
  senderId: string
}

export type FriendsAcceptFriendRequestResponse = Message

export type FriendsDeclineFriendRequestData = {
  senderId: string
}

export type FriendsDeclineFriendRequestResponse = Message

export type FriendsCancelFriendRequestData = {
  receiverId: string
}

export type FriendsCancelFriendRequestResponse = Message

export type FriendsRemoveFriendData = {
  friendId: string
}

export type FriendsRemoveFriendResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MeGetCurrentUserResponse = UserPublic

export type MeDeleteUserMeResponse = Message

export type MeUpdateUserMeData = {
  requestBody: UserUpdate
}

export type MeUpdateUserMeResponse = UserPublic

export type MeUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type MeUpdatePasswordMeResponse = Message

export type MeGetMyShowtimesData = {
  limit?: number
  offset?: number
  snapshotTime?: string
}

export type MeGetMyShowtimesResponse = Array<ShowtimeLoggedIn>

export type MeSyncWatchlistResponse = Message

export type MeGetFriendsResponse = Array<UserWithFriendStatus>

export type MeGetSentFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetReceivedFriendRequestsResponse = Array<UserWithFriendStatus>

export type MeGetCinemaSelectionsResponse = Array<number>

export type MeSetCinemaSelectionsData = {
  requestBody: Array<number>
}

export type MeSetCinemaSelectionsResponse = Message

export type MoviesReadMoviesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  showtimeLimit?: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string
  timeRanges?: Array<string> | null
  watchlistOnly?: boolean
}

export type MoviesReadMoviesResponse = Array<MovieSummaryLoggedIn>

export type MoviesReadMovieData = {
  days?: Array<string> | null
  id: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string
  timeRanges?: Array<string> | null
  watchlistOnly?: boolean
}

export type MoviesReadMovieResponse = MovieLoggedIn

export type ShowtimesUpdateShowtimeSelectionData = {
  days?: Array<string> | null
  query?: string | null
  requestBody: ShowtimeSelectionUpdate
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  showtimeId: number
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string
  timeRanges?: Array<string> | null
  watchlistOnly?: boolean
}

export type ShowtimesUpdateShowtimeSelectionResponse = ShowtimeLoggedIn

export type ShowtimesGetMainPageShowtimesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string
  timeRanges?: Array<string> | null
  watchlistOnly?: boolean
}

export type ShowtimesGetMainPageShowtimesResponse = Array<ShowtimeLoggedIn>

export type UsersSearchUsersData = {
  limit?: number
  offset?: number
  query: string
}

export type UsersSearchUsersResponse = Array<UserWithFriendStatus>

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersGetUserData = {
  userId: string
}

export type UsersGetUserResponse = UserPublic

export type UsersGetUserSelectedShowtimesData = {
  days?: Array<string> | null
  limit?: number
  offset?: number
  query?: string | null
  /**
   * Filter showtimes to only these cinema IDs
   */
  selectedCinemaIds?: Array<number> | null
  /**
   * Only show showtimes after this moment
   */
  snapshotTime?: string
  timeRanges?: Array<string> | null
  userId: string
  watchlistOnly?: boolean
}

export type UsersGetUserSelectedShowtimesResponse = Array<ShowtimeLoggedIn>

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
