/**
 * Admin feature component: ScrapeMonitor. Per-stream scrape-run history with
 * deltas and anomaly flags, plus the stored per-run recaps — so a source that
 * suddenly finds far fewer showtimes, a degraded run, or deletions is easy to
 * trace. The same data is available as raw JSON at the API paths shown below,
 * for scripts/LLMs to parse.
 */
import {
  Badge,
  Box,
  Button,
  Code,
  Heading,
  SimpleGrid,
  Stack,
  Stat,
  Table,
  Text,
} from "@chakra-ui/react"
import { useQuery } from "@tanstack/react-query"
import { Link } from "@tanstack/react-router"
import { useState } from "react"

import { AdminService } from "shared"

import type { ScrapeRunView } from "shared"

const AdminNav = () => (
  <Stack direction="row" gap={2} mb={6}>
    <Button asChild size="sm" variant="outline">
      <Link to="/admin">Overview</Link>
    </Button>
    <Button asChild size="sm" variant="outline">
      <Link to="/admin/movies">Movies</Link>
    </Button>
    <Button asChild size="sm" variant="outline">
      <Link to="/admin/showtimes">Showtimes</Link>
    </Button>
    <Button asChild size="sm" variant="outline">
      <Link to="/admin/reports">Reports</Link>
    </Button>
    <Button asChild size="sm" variant="outline">
      <Link to="/admin/scrapes">Scrapes</Link>
    </Button>
  </Stack>
)

const WINDOW_OPTIONS: { label: string; hours: number }[] = [
  { label: "24h", hours: 24 },
  { label: "48h", hours: 48 },
  { label: "7d", hours: 24 * 7 },
]

const anomalyBadges = (run: ScrapeRunView) => {
  const badges: { label: string; color: string }[] = []
  if (run.is_failed) badges.push({ label: "failed", color: "red" })
  if (run.is_degraded) badges.push({ label: "degraded", color: "orange" })
  if (run.is_zero_observed) badges.push({ label: "zero", color: "red" })
  if (run.is_big_drop) badges.push({ label: "big drop", color: "orange" })
  return badges
}

const formatDelta = (delta: number | null) => {
  if (delta === null) return "—"
  if (delta > 0) return `+${delta}`
  return `${delta}`
}

const RunsTable = ({ runs }: { runs: ScrapeRunView[] }) => (
  <Box overflowX="auto">
    <Table.Root size="sm">
      <Table.Header>
        <Table.Row>
          <Table.ColumnHeader>Started</Table.ColumnHeader>
          <Table.ColumnHeader>Source</Table.ColumnHeader>
          <Table.ColumnHeader>Status</Table.ColumnHeader>
          <Table.ColumnHeader>Observed</Table.ColumnHeader>
          <Table.ColumnHeader>Prev</Table.ColumnHeader>
          <Table.ColumnHeader>Δ</Table.ColumnHeader>
          <Table.ColumnHeader>Flags</Table.ColumnHeader>
          <Table.ColumnHeader>Error</Table.ColumnHeader>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {runs.map((run) => {
          const badges = anomalyBadges(run)
          return (
            <Table.Row
              key={run.id}
              bg={run.is_anomaly ? "red.subtle" : undefined}
            >
              <Table.Cell whiteSpace="nowrap">
                {run.started_at.replace("T", " ").slice(0, 16)}
              </Table.Cell>
              <Table.Cell>{run.source_label}</Table.Cell>
              <Table.Cell>{run.status}</Table.Cell>
              <Table.Cell>{run.observed_showtime_count ?? "—"}</Table.Cell>
              <Table.Cell>{run.previous_observed_count ?? "—"}</Table.Cell>
              <Table.Cell
                color={
                  run.delta !== null && run.delta < 0 ? "red.fg" : undefined
                }
              >
                {formatDelta(run.delta)}
              </Table.Cell>
              <Table.Cell>
                <Stack direction="row" gap={1}>
                  {badges.map((badge) => (
                    <Badge key={badge.label} colorPalette={badge.color}>
                      {badge.label}
                    </Badge>
                  ))}
                </Stack>
              </Table.Cell>
              <Table.Cell maxW="360px" truncate title={run.error ?? ""}>
                {run.error ?? ""}
              </Table.Cell>
            </Table.Row>
          )
        })}
      </Table.Body>
    </Table.Root>
  </Box>
)

const RecapViewer = ({ recapId }: { recapId: number }) => {
  const { data: recap, isLoading } = useQuery({
    queryKey: ["admin", "scrape-recap", recapId],
    queryFn: () => AdminService.getScrapeRecap({ recapId }),
  })
  if (isLoading || !recap) return <Text>Loading recap…</Text>
  return (
    <Box
      mt={4}
      p={4}
      borderWidth="1px"
      borderRadius="md"
      maxH="600px"
      overflowY="auto"
    >
      {/* Recap HTML is generated by our own scraper (superuser-only view). */}
      <Box
        // biome-ignore lint/security/noDangerouslySetInnerHtml: trusted, server-generated recap HTML
        dangerouslySetInnerHTML={{ __html: recap.html }}
      />
    </Box>
  )
}

const ScrapeMonitor = () => {
  const [hours, setHours] = useState(48)
  const [openRecapId, setOpenRecapId] = useState<number | null>(null)

  const { data, isLoading } = useQuery({
    queryKey: ["admin", "scrape-runs", hours],
    queryFn: () => AdminService.getScrapeRuns({ hours }),
  })
  const { data: recaps } = useQuery({
    queryKey: ["admin", "scrape-recaps"],
    queryFn: () => AdminService.listScrapeRecaps({ limit: 30 }),
  })

  return (
    <Box>
      <AdminNav />
      <Heading size="lg" mb={2}>
        Scrape Monitor
      </Heading>
      <Text color="fg.muted" mb={4}>
        Raw JSON for scripts/LLMs:{" "}
        <Code>/api/v1/admin/scrape/runs?hours={hours}</Code> and{" "}
        <Code>/api/v1/admin/scrape/recaps</Code>
      </Text>

      <Stack direction="row" gap={2} mb={4}>
        {WINDOW_OPTIONS.map((option) => (
          <Button
            key={option.hours}
            size="sm"
            variant={hours === option.hours ? "solid" : "outline"}
            onClick={() => setHours(option.hours)}
          >
            {option.label}
          </Button>
        ))}
        <Button
          size="sm"
          variant="outline"
          onClick={() =>
            navigator.clipboard.writeText(JSON.stringify(data, null, 2))
          }
          disabled={!data}
        >
          Copy JSON
        </Button>
      </Stack>

      {isLoading || !data ? (
        <Text>Loading scrape runs…</Text>
      ) : (
        <>
          <SimpleGrid columns={{ base: 2, md: 4 }} gap={4} mb={6}>
            <Stat.Root>
              <Stat.Label>Runs</Stat.Label>
              <Stat.ValueText>{data.summary.total_runs}</Stat.ValueText>
            </Stat.Root>
            <Stat.Root>
              <Stat.Label>Failed</Stat.Label>
              <Stat.ValueText>{data.summary.failed_runs}</Stat.ValueText>
            </Stat.Root>
            <Stat.Root>
              <Stat.Label>Degraded</Stat.Label>
              <Stat.ValueText>{data.summary.degraded_runs}</Stat.ValueText>
            </Stat.Root>
            <Stat.Root>
              <Stat.Label>Anomalies</Stat.Label>
              <Stat.ValueText>{data.summary.anomaly_runs}</Stat.ValueText>
            </Stat.Root>
          </SimpleGrid>

          {data.summary.streams_with_anomalies.length > 0 && (
            <Box mb={4}>
              <Text fontWeight="semibold" mb={1}>
                Streams with anomalies:
              </Text>
              <Stack direction="row" gap={1} wrap="wrap">
                {data.summary.streams_with_anomalies.map((stream) => (
                  <Badge key={stream} colorPalette="orange">
                    {stream}
                  </Badge>
                ))}
              </Stack>
            </Box>
          )}

          <RunsTable runs={data.runs} />
        </>
      )}

      <Heading size="md" mt={8} mb={2}>
        Daily recaps
      </Heading>
      <Stack gap={1}>
        {(recaps ?? []).map((recap) => (
          <Button
            key={recap.id}
            size="sm"
            variant={openRecapId === recap.id ? "solid" : "ghost"}
            justifyContent="flex-start"
            onClick={() =>
              setOpenRecapId(openRecapId === recap.id ? null : recap.id)
            }
          >
            {recap.subject}
          </Button>
        ))}
      </Stack>
      {openRecapId !== null && <RecapViewer recapId={openRecapId} />}
    </Box>
  )
}

export default ScrapeMonitor
