"""add ticket_link

Revision ID: 0505e57200e5
Revises: 7599b54ed9f6
Create Date: 2025-07-02 01:00:00.983862

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0505e57200e5'
down_revision = '7599b54ed9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
