"""change watchlist selection to with letterboxd username

Revision ID: 1e8d74a3d936
Revises: 5b62b864ffde
Create Date: 2025-08-03 13:32:07.152927

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1e8d74a3d936'
down_revision = '5b62b864ffde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlistselection', sa.Column('letterboxd_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('watchlistselection_user_id_fkey', 'watchlistselection', type_='foreignkey')
    op.create_foreign_key(None, 'watchlistselection', 'letterboxd', ['letterboxd_username'], ['letterboxd_username'])
    op.drop_column('watchlistselection', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlistselection', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'watchlistselection', type_='foreignkey')
    op.create_foreign_key('watchlistselection_user_id_fkey', 'watchlistselection', 'user', ['user_id'], ['id'])
    op.drop_column('watchlistselection', 'letterboxd_username')
    # ### end Alembic commands ###
