"""add cinema selection table

Revision ID: 20b11404f4e7
Revises: 6bca84c3862a
Create Date: 2025-08-04 23:25:22.377807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '20b11404f4e7'
down_revision = '6bca84c3862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemaselection',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cinema_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinemaselection')
    # ### end Alembic commands ###
