"""add ticket_link

Revision ID: 3454bed2d621
Revises: b98b7443fbbc
Create Date: 2025-07-08 12:38:11.236671

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3454bed2d621'
down_revision = 'b98b7443fbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
