"""fixed foreign key on letterboxd username?

Revision ID: 38d9598f731b
Revises: 33c5b06e9933
Create Date: 2025-08-03 11:45:05.459468

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '38d9598f731b'
down_revision = '33c5b06e9933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
