"""index showtime datetime

Revision ID: 396cc2bb8267
Revises: f7a3aaa81617
Create Date: 2025-08-06 17:25:55.368740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '396cc2bb8267'
down_revision = 'f7a3aaa81617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_showtime_datetime'), 'showtime', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showtime_datetime'), table_name='showtime')
    # ### end Alembic commands ###
