"""removed status from friend request

Revision ID: 3f524ca5f354
Revises: 00974644fffc
Create Date: 2025-08-02 23:40:07.852428

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f524ca5f354'
down_revision = '00974644fffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.alter_column('cinema', 'badge_bg_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cinema', 'badge_text_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cinema', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('friendrequest', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendrequest', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('cinema', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cinema', 'badge_text_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cinema', 'badge_bg_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
