"""Create movie table

Revision ID: 434743b85a73
Revises: d9367cd0c45b
Create Date: 2025-06-29 23:45:11.371321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '434743b85a73'
down_revision = 'd9367cd0c45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
