"""add ticket_link

Revision ID: 44fad4d252cf
Revises: 0505e57200e5
Create Date: 2025-07-02 01:02:02.470396

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44fad4d252cf'
down_revision = '0505e57200e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtimeselection',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'showtime_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtimeselection')
    # ### end Alembic commands ###
