"""add ticket_link

Revision ID: 4e179c17378d
Revises: 5af13ee3d4c0
Create Date: 2025-06-30 12:34:57.021033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e179c17378d'
down_revision = '5af13ee3d4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('ticket_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtime', 'ticket_link')
    # ### end Alembic commands ###
