"""add city/cinema

Revision ID: 50a0373d9e24
Revises: 3454bed2d621
Create Date: 2025-07-08 12:38:35.269983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50a0373d9e24'
down_revision = '3454bed2d621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
