"""Add letterboxd_username to User model

Revision ID: 52c75363d859
Revises: a2271b3f652f
Create Date: 2025-07-18 17:00:36.363189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52c75363d859'
down_revision = 'a2271b3f652f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('letterboxd_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'letterboxd_username')
    # ### end Alembic commands ###
