"""add cinema url

Revision ID: 52cdad11ec8b
Revises: 0b67ba1bd211
Create Date: 2025-07-08 13:49:21.874047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52cdad11ec8b'
down_revision = '0b67ba1bd211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema', 'url')
    # ### end Alembic commands ###
