"""add ticket_link

Revision ID: 57507828d0d9
Revises: 58768c5bd5cf
Create Date: 2025-07-01 18:06:08.261774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57507828d0d9'
down_revision = '58768c5bd5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
