"""fixed foreign key on letterboxd username?

Revision ID: 5b62b864ffde
Revises: 38d9598f731b
Create Date: 2025-08-03 11:47:04.671170

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b62b864ffde'
down_revision = '38d9598f731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('letterboxd_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_user_letterboxd_username'), 'user', ['letterboxd_username'], unique=True)
    op.create_foreign_key(None, 'user', 'letterboxd', ['letterboxd_username'], ['letterboxd_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_letterboxd_username'), table_name='user')
    op.drop_column('user', 'letterboxd_username')
    # ### end Alembic commands ###
