"""add cinema to showtime

Revision ID: 66dc1c51b6ae
Revises: 52cdad11ec8b
Create Date: 2025-07-08 14:48:24.495797

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66dc1c51b6ae'
down_revision = '52cdad11ec8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('cinema_id', sa.Integer(), nullable=False))
    op.drop_index('ix_showtime_id', table_name='showtime')
    op.drop_constraint('uq_showtime_unique_fields', 'showtime', type_='unique')
    op.create_unique_constraint('uq_showtime_unique_fields', 'showtime', ['cinema_id', 'datetime', 'theatre', 'movie_id'])
    op.create_foreign_key(None, 'showtime', 'cinema', ['cinema_id'], ['id'])
    op.drop_column('showtime', 'cinema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('cinema', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'showtime', type_='foreignkey')
    op.drop_constraint('uq_showtime_unique_fields', 'showtime', type_='unique')
    op.create_unique_constraint('uq_showtime_unique_fields', 'showtime', ['cinema', 'datetime', 'theatre', 'movie_id'])
    op.create_index('ix_showtime_id', 'showtime', ['id'], unique=True)
    op.drop_column('showtime', 'cinema_id')
    # ### end Alembic commands ###
