"""does it still work?

Revision ID: 6bca84c3862a
Revises: b645e9cd04aa
Create Date: 2025-08-03 17:40:09.581709

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6bca84c3862a'
down_revision = 'b645e9cd04aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
