"""add ticket_link

Revision ID: 7599b54ed9f6
Revises: 57507828d0d9
Create Date: 2025-07-02 00:54:51.647616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7599b54ed9f6'
down_revision = '57507828d0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
