"""added letterboxd table

Revision ID: 791f93f2b8ff
Revises: 3f524ca5f354
Create Date: 2025-08-03 11:32:54.765042

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '791f93f2b8ff'
down_revision = '3f524ca5f354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letterboxd',
    sa.Column('letterboxd_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_watchlist_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('letterboxd_username')
    )
    op.drop_column('user', 'last_watchlist_sync')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_watchlist_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('letterboxd')
    # ### end Alembic commands ###
