"""add going status

Revision ID: 86dcd90174a0
Revises: e759639a408d
Create Date: 2025-12-23 15:14:54.334502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86dcd90174a0'
down_revision = 'e759639a408d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimeselection', sa.Column('going_status', sa.Enum('GOING', 'NOT_GOING', 'INTERESTED', name='goingstatus', native_enum=False), nullable=False, server_default='GOING'))
    op.drop_constraint('showtimeselection_showtime_id_fkey', 'showtimeselection', type_='foreignkey')
    op.create_foreign_key(None, 'showtimeselection', 'showtime', ['showtime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'showtimeselection', type_='foreignkey')
    op.create_foreign_key('showtimeselection_showtime_id_fkey', 'showtimeselection', 'showtime', ['showtime_id'], ['id'], ondelete='CASCADE')
    op.drop_column('showtimeselection', 'going_status')
    # ### end Alembic commands ###
