"""add ticket_link

Revision ID: a894bfa5f066
Revises: de5a631cca63
Create Date: 2025-07-01 15:54:00.232474

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a894bfa5f066'
down_revision = 'de5a631cca63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('user', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
