"""set primary keys in watchlist selection?

Revision ID: b645e9cd04aa
Revises: 1e8d74a3d936
Create Date: 2025-08-03 17:35:57.449773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b645e9cd04aa'
down_revision = '1e8d74a3d936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "watchlistselection_pkey",
        "watchlistselection",
        ["letterboxd_username", "movie_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("watchlistselection_pkey", "watchlistselection", type_="primary")
    # ### end Alembic commands ###
