"""add ticket_link

Revision ID: b98b7443fbbc
Revises: 44fad4d252cf
Create Date: 2025-07-03 15:55:56.032971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b98b7443fbbc'
down_revision = '44fad4d252cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
