"""index showtime datetime

Revision ID: d1569b377429
Revises: 396cc2bb8267
Create Date: 2025-08-07 00:30:41.358181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd1569b377429'
down_revision = '396cc2bb8267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
