"""Create movie table

Revision ID: d9367cd0c45b
Revises: df3fd8e26448
Create Date: 2025-06-29 16:43:16.730012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9367cd0c45b'
down_revision = 'df3fd8e26448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_showtime_unique_fields', 'showtime', ['cinema', 'datetime', 'theatre', 'movie_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_showtime_unique_fields', 'showtime', type_='unique')
    # ### end Alembic commands ###
