"""add ticket_link

Revision ID: de5a631cca63
Revises: 4e179c17378d
Create Date: 2025-06-30 14:59:50.285519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'de5a631cca63'
down_revision = '4e179c17378d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
