"""Create movie table

Revision ID: df3fd8e26448
Revises: 0e2cdaeda7f2
Create Date: 2025-06-29 16:24:22.786479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'df3fd8e26448'
down_revision = '0e2cdaeda7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('cinema', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theatre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showtime_id'), 'showtime', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_showtime_id'), table_name='showtime')
    op.drop_table('showtime')
    # ### end Alembic commands ###
