"""index showtime datetime

Revision ID: f7a3aaa81617
Revises: 20b11404f4e7
Create Date: 2025-08-06 17:24:36.633215

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7a3aaa81617'
down_revision = '20b11404f4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
