"""add letterboxd data

Revision ID: f947e046d6bb
Revises: ab95bab510cd
Create Date: 2025-08-28 17:45:20.077583

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f947e046d6bb'
down_revision = 'ab95bab510cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('movie', sa.Column('top250', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('directors', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('movie', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'rating')
    op.drop_column('movie', 'release_year')
    op.drop_column('movie', 'directors')
    op.drop_column('movie', 'top250')
    op.drop_column('movie', 'original_title')
    # ### end Alembic commands ###
