/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMoviesRouteImport } from './routes/_layout/movies'
import { Route as LayoutFriendsRouteImport } from './routes/_layout/friends'
import { Route as LayoutMeShowtimesRouteImport } from './routes/_layout/me/showtimes'
import { Route as LayoutUserIdShowtimesRouteImport } from './routes/_layout/$userId/showtimes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesRoute = LayoutMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFriendsRoute = LayoutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMeShowtimesRoute = LayoutMeShowtimesRouteImport.update({
  id: '/me/showtimes',
  path: '/me/showtimes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUserIdShowtimesRoute = LayoutUserIdShowtimesRouteImport.update({
  id: '/$userId/showtimes',
  path: '/$userId/showtimes',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/friends': typeof LayoutFriendsRoute
  '/movies': typeof LayoutMoviesRoute
  '/settings': typeof LayoutSettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/$userId/showtimes': typeof LayoutUserIdShowtimesRoute
  '/me/showtimes': typeof LayoutMeShowtimesRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/friends': typeof LayoutFriendsRoute
  '/movies': typeof LayoutMoviesRoute
  '/settings': typeof LayoutSettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/': typeof LayoutIndexRoute
  '/$userId/showtimes': typeof LayoutUserIdShowtimesRoute
  '/me/showtimes': typeof LayoutMeShowtimesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/friends': typeof LayoutFriendsRoute
  '/_layout/movies': typeof LayoutMoviesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$userId/showtimes': typeof LayoutUserIdShowtimesRoute
  '/_layout/me/showtimes': typeof LayoutMeShowtimesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/friends'
    | '/movies'
    | '/settings'
    | '/movie/$movieId'
    | '/$userId/showtimes'
    | '/me/showtimes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/friends'
    | '/movies'
    | '/settings'
    | '/movie/$movieId'
    | '/'
    | '/$userId/showtimes'
    | '/me/showtimes'
  id:
    | '__root__'
    | '/_layout'
    | '/forbidden'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/friends'
    | '/_layout/movies'
    | '/_layout/settings'
    | '/movie/$movieId'
    | '/_layout/'
    | '/_layout/$userId/showtimes'
    | '/_layout/me/showtimes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies': {
      id: '/_layout/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof LayoutMoviesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/friends': {
      id: '/_layout/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof LayoutFriendsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/me/showtimes': {
      id: '/_layout/me/showtimes'
      path: '/me/showtimes'
      fullPath: '/me/showtimes'
      preLoaderRoute: typeof LayoutMeShowtimesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$userId/showtimes': {
      id: '/_layout/$userId/showtimes'
      path: '/$userId/showtimes'
      fullPath: '/$userId/showtimes'
      preLoaderRoute: typeof LayoutUserIdShowtimesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutFriendsRoute: typeof LayoutFriendsRoute
  LayoutMoviesRoute: typeof LayoutMoviesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutUserIdShowtimesRoute: typeof LayoutUserIdShowtimesRoute
  LayoutMeShowtimesRoute: typeof LayoutMeShowtimesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFriendsRoute: LayoutFriendsRoute,
  LayoutMoviesRoute: LayoutMoviesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutUserIdShowtimesRoute: LayoutUserIdShowtimesRoute,
  LayoutMeShowtimesRoute: LayoutMeShowtimesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
