name: Generate Client

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    # For PRs from forks
    - uses: actions/checkout@v4
    # For PRs from the same repo
    - uses: actions/checkout@v4
      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.CI_PAT }}
    - name: Create .env file
      run: |
        cat > .env <<EOF
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        STACK_NAME=${{ secrets.STACK_NAME }}
        FRONTEND_HOST=${{ vars.FRONTEND_HOST }}
        DOMAIN=${{ vars.DOMAIN }}
        DOCKER_IMAGE_BACKEND=${{ vars.DOCKER_IMAGE_BACKEND }}
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        ENVIRONMENT=${{ vars.ENVIRONMENT }}
        BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
        FIRST_SUPERUSER=admin@example.com
        POSTGRES_SERVER=localhost
        POSTGRES_PORT=5432
        PROJECT_NAME="MikiBoxd"
        DOCKER_IMAGE_FRONTEND=frontend
        FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}
        SMTP_HOST=
        SMTP_USER=
        SMTP_PASSWORD=
        EMAILS_FROM_EMAIL=info@example.com
        SMTP_TLS=True
        SMTP_SSL=False
        SMTP_PORT=587
        SENTRY_DSN=
        DEBUG=False
        TMDB_KEY=${{ secrets.TMDB_KEY }}
        TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}
        ENABLE_TELEGRAM=false
        EOF
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.4.15"
        enable-cache: true
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    - run: uv sync
      working-directory: backend
    - run: uv run bash scripts/generate-client.sh
      env:
        VIRTUAL_ENV: backend/.venv
        SECRET_KEY: just-for-generating-client
        POSTGRES_PASSWORD: just-for-generating-client
        FIRST_SUPERUSER_PASSWORD: just-for-generating-client
    - name: Add changes to git
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add frontend/src/client
    # Same repo PRs
    - name: Push changes
      if: ( github.event_name != 'pull_request' || github.secret_source == 'Actions' )
      run: |
        git diff --staged --quiet || git commit -m "✨ Autogenerate frontend client"
        git push
    # Fork PRs
    - name: Check changes
      if: ( github.event_name == 'pull_request' && github.secret_source != 'Actions' )
      run: |
        git diff --staged --quiet || (echo "Changes detected in generated client, run scripts/generate-client.sh and commit the changes" && exit 1)
