name: Labels
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      # For label-checker
      - labeled
      - unlabeled

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}
    - run: echo "Done adding labels"
    - name: Add labels based on branch name
      uses: actions/github-script@v7
      with:
        script: |
          const branch = context.payload.pull_request.head.ref.toLowerCase();
          console.log(Branch name: ${branch});
          const labels = [];

          if (branch.startsWith('feature/') || branch.startsWith('feat/')) {
            labels.push('feature');
          } else if (branch.startsWith('bug/') || branch.startsWith('fix/') || branch.startsWith('hotfix/')) {
            labels.push('bug');
          } else if (branch.startsWith('enhancement/') || branch.startsWith('improvement/')) {
            labels.push('enhancement');
            console.log('Matched enhancement label');
          } else if (branch.startsWith('refactor/')) {
            labels.push('refactor');
          } else if (branch.startsWith('test/') || branch.startsWith('tests/')) {
            labels.push('test');
          } else if (branch.startsWith('perf/') || branch.startsWith('performance/') || branch.startsWith('optimize/')) {
            labels.push('performance');
          }

          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });
            console.log(Applied labels: ${labels.join(', ')});
          } else {
            console.log('No matching branch label found.');
          }
    - run: echo "Done adding labels"
  # Run this after labeler applied labels
  check-labels:
    needs:
      - labeler
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: breaking,security,feature,bug,refactor,upgrade,docs,lang-all,internal
          repo_token: ${{ secrets.GITHUB_TOKEN }}
