name: Test Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          cat > .env <<EOF
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          STACK_NAME=${{ secrets.STACK_NAME }}
          FRONTEND_HOST=${{ vars.FRONTEND_HOST }}
          DOMAIN=${{ vars.DOMAIN }}
          DOCKER_IMAGE_BACKEND=${{ vars.DOCKER_IMAGE_BACKEND }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ENVIRONMENT=${{ vars.ENVIRONMENT }}
          BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
          FIRST_SUPERUSER=admin@example.com
          POSTGRES_SERVER=localhost
          POSTGRES_PORT=5432
          PROJECT_NAME="MikiBoxd"
          DOCKER_IMAGE_FRONTEND=frontend
          FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}
          SMTP_HOST=
          SMTP_USER=
          SMTP_PASSWORD=
          EMAILS_FROM_EMAIL=info@example.com
          SMTP_TLS=True
          SMTP_SSL=False
          SMTP_PORT=587
          SENTRY_DSN=
          DEBUG=False
          TMDB_KEY=${{ secrets.TMDB_KEY }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}
          ENABLE_TELEGRAM=false
          EOF
      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - name: Try starting backend
        run: |
          docker compose up -d --wait backend frontend adminer || True
          docker compose ps
          docker compose logs backend
      - name: Test backend is up
        run: curl http://localhost:8000/api/v1/utils/health-check
      - name: Test frontend is up
        run: curl http://localhost:5173
      - run: docker compose down -v --remove-orphans
